# Name your project! Project names should contain only lowercase characters
        # and underscores. A good package name should reflect your organization's
        # name or the intended use of these models
        name: 'dbt_model_generation'
        version: '1.0.0'
        config-version: 2
        
        # This setting configures which "profile" dbt uses for this project.
        profile: 'dbt_model_generation'

        quoting:
        database: true
        schema: true
        identifier: false
        
        vars:
        dbt_model_generation:
          DWH_TABLE:
            backfill_flag: "false"
            backfill_start_date: "2022-01-01"
            incremental_days: "366"
            backfill_end_date: "2022-01-02"
        
        # These configurations specify where dbt should look for different types of files.
        # The `model-paths` config, for example, states that models in this project can be
        # found in the "models/" directory. You probably won't need to change these!
        model-paths: ["models"]
        analysis-paths: ["analyses"]
        test-paths: ["tests"]
        seed-paths: ["seeds"]
        macro-paths: ["macros"]
        snapshot-paths: ["PresentationLayer"]
        
        target-path: "target"  # directory which will store compiled SQL files
        clean-targets:         # directories to be removed by `dbt clean`
        - "target"
        - "dbt_packages"
        
        # on-run-start: create table if not exists int.DBTExecutionLog (DBTId varchar, DBTRunStartTime TIMESTAMP, DBTRunEndTime TIMESTAMP, DBTStatus varchar, TotalTimeTakenInSeconds int); INSERT INTO int.DBTExecutionLog VALUES ('{{invocation_id}}',current_timestamp(),NULL,'Started',NULL);create table if not exists int.dbtsteplog (invocationid varchar,tablename varchar, stepstart timestamp default current_timestamp(),stepend timestamp ,stepstatus varchar);
        # on-run-end: UPDATE int.DBTExecutionLog SET DBTRunEndTime = current_timestamp(), DBTStatus = 'Successful' WHERE DBTId = '{{invocation_id}}';
        
        # Configuring models
        # Full documentation: https://docs.getdbt.com/docs/configuring-models
        
        # In this example config, we tell dbt to build all models in the example/ directory
        # as tables. These settings can be overridden in the individual model files
        models:
          dbt_model_generation:
            # Config indicated by + and applies to all files under models/example/
              +meta:
                example:
                  +materialized: view
            flags:
            require_generic_test_arguments_property: true
        