dbt_model_generation:
    outputs:
      dev:
        account: AJONJJB-BQB66912
        database: BSL_MA
        password: Shajahan@snowflake_2002
        role: ACCOUNTADMIN
        schema: DWH_MA
        threads: 1
        type: snowflake
        user: SHAJAHAN
        warehouse: COMPUTE_WH
    target: dev
        