{#
------------------------------------------------------------------------
MODEL NAME    : dim_customer
TARGET TABLE  : BSL_MA.DWH_MA.DIM_CUSTOMER
SOURCE TABLES : BSL_RAW.DWH_RAW.CUSTOMERS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : Customer dimension table with customer details and derived
                spending tier based on order history
PREREQUISITES : Source tables CUSTOMERS and ORDERS must be available
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-25
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'view'
) }}

WITH customers_source AS (
    SELECT
        customer_id,
        first_name, -- auto corrected using semantic file
        last_name, -- auto corrected using semantic file
        email,
        created_at,
        inserted_at
    FROM {{ source('dwh_raw', 'customers') }}
    {% if var('models')['backfill_flag'] == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("models")["backfill_start_date"] }}' AND '{{ var("models")["backfill_end_date"] }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > (SELECT MAX(inserted_at) FROM {{ this }})
        {% endif %}
    {% endif %}
),

orders_source AS (
    SELECT
        customer_id,
        total_amount,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
    WHERE order_date >= CURRENT_DATE - 365
),

customer_spending AS (
    SELECT
        customers.customer_id,
        COALESCE(SUM(orders.total_amount), 0) AS total_spending_365_days
    FROM customers_source AS customers
    LEFT JOIN orders_source AS orders
        ON customers.customer_id = orders.customer_id
    GROUP BY customers.customer_id
),

transformed AS (
    SELECT
        customers.customer_id,
        TRIM(UPPER(customers.first_name)) AS first_name,
        TRIM(UPPER(customers.last_name)) AS last_name,
        CASE 
            WHEN REGEXP_LIKE(LOWER(customers.email), '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')
            THEN LOWER(customers.email)
            ELSE NULL
        END AS email,
        customers.created_at::DATE AS customer_since_date,
        CASE 
            WHEN spending.total_spending_365_days >= 1000 THEN 'Gold'
            WHEN spending.total_spending_365_days >= 500 THEN 'Silver'
            ELSE 'Bronze'
        END AS customer_tier,
        COALESCE(customers.inserted_at, CURRENT_DATE) AS last_updated
    FROM customers_source AS customers
    LEFT JOIN customer_spending AS spending
        ON customers.customer_id = spending.customer_id
)

SELECT * FROM transformed