{#
------------------------------------------------------------------------
MODEL NAME    : dim_category
TARGET TABLE  : BSL_MA.DWH_MA.DIM_CATEGORY
SOURCE TABLES : BSL_RAW.DWH_RAW.CATEGORIES
DESCRIPTION   : Dimension table for categories with hierarchical path 
                building up to 2 levels and proper data transformations
PREREQUISITES : Source table CATEGORIES must exist in BSL_RAW.DWH_RAW
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2025-11-21
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_categories as (
    select 
        category_id,
        category_name,
        parent_category_id,
        is_active,
        inserted_at
    from {{ source('dwh_raw', 'categories') }}
),

parent_categories as (
    select 
        category_id as parent_cat_id,
        category_name as parent_category_name
    from {{ source('dwh_raw', 'categories') }}
),

transformed_categories as (
    select 
        src.category_id,
        trim(initcap(src.category_name)) as category_name,
        src.parent_category_id,
        case 
            when src.parent_category_id is not null 
            then concat(parent.parent_category_name, ' > ', trim(initcap(src.category_name)))
            else trim(initcap(src.category_name))
        end as category_path,
        coalesce(src.is_active, true) as is_active, -- Auto corrected using semantic file: default true if null
        src.inserted_at as last_updated
    from source_categories src
    left join parent_categories parent 
        on src.parent_category_id = parent.parent_cat_id
)

select 
    category_id,
    category_name,
    parent_category_id,
    category_path,
    is_active,
    last_updated
from transformed_categories