{#
------------------------------------------------------------------------
MODEL NAME    : dim_product
TARGET TABLE  : BSL_MA.DWH_MA.DIM_PRODUCT
SOURCE TABLES : BSL_RAW.DWH_RAW.PRODUCTS
DESCRIPTION   : Dimension table for products containing product details,
                pricing information, and price bands for analytical purposes
PREREQUISITES : Source table PRODUCTS must exist with required columns
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-27
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    unique_key = 'product_id',
    incremental_strategy = 'merge'
) }}

WITH source_data AS (
    SELECT
        product_id,
        product_name,
        price,
        inserted_at
    FROM {{ source('dwh_raw', 'products') }}
    {% if var('backfill_flag') == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("backfill_start_date") }}' AND '{{ var("backfill_end_date") }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > COALESCE( (SELECT MAX(last_updated) FROM BSL_MA.DWH_MA.dim_product), TO_DATE('0001-01-01'))
        {% endif %}
    {% endif %}
),

transformed AS (
    SELECT
        product_id,
        -- Title-case product name and trim excessive spaces
        INITCAP(TRIM(REGEXP_REPLACE(product_name, '\\s+', ' '))) AS product_name,
        -- Direct mapping with precision specification
        CAST(price AS NUMBER(10,2)) AS price,
        -- Price band logic: 'Low' < 50, 'Mid' 50–199.99, 'High' 200–499.99, 'Premium' >= 500
        CASE 
            WHEN price < 50 THEN 'Low'
            WHEN price >= 50 AND price <= 199.99 THEN 'Mid'
            WHEN price >= 200 AND price <= 499.99 THEN 'High'
            WHEN price >= 500 THEN 'Premium'
            ELSE 'Unknown'
        END AS price_band,
        -- Direct mapping for last_updated
        inserted_at AS last_updated
    FROM source_data
)

SELECT * FROM transformed