{#
------------------------------------------------------------------------
MODEL NAME    : dim_address
TARGET TABLE  : BSL_MA.DWH_MA.DIM_ADDRESS
SOURCE TABLES : BSL_RAW.DWH_RAW.ADDRESSES, BSL_MA.DWH_MA.DIM_CUSTOMER
DESCRIPTION   : Dimension table for addresses with customer lookup and 
                data transformations including trimming whitespace and 
                converting city names to uppercase
PREREQUISITES : dim_customer table must exist for customer lookup
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2025-11-20
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_addresses as (
    select 
        address_id,
        customer_id,
        address_line1,
        city,
        country,
        inserted_at
    from {{ source('dwh_raw', 'addresses') }}
),

customer_lookup as (
    select 
        customer_id
    from {{ ref('dim_customer') }}
),

transformed_addresses as (
    select 
        src_addr.address_id,
        src_addr.customer_id,
        trim(src_addr.address_line1) as address_line1,
        upper(src_addr.city) as city,
        src_addr.country,
        src_addr.inserted_at::date as inserted_at
    from source_addresses src_addr
    inner join customer_lookup cust_lookup
        on src_addr.customer_id = cust_lookup.customer_id
)

select * from transformed_addresses