{#
------------------------------------------------------------------------
MODEL NAME    : dim_category
TARGET TABLE  : bsl_ma.dwh_ma.dim_category
SOURCE TABLES : bsl_raw.dwh_raw.categories
DESCRIPTION   : Dimension table for product categories with hierarchical 
                path structure up to 2 levels
PREREQUISITES : Source table bsl_raw.dwh_raw.categories must exist
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2025-11-17
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_categories as (
    select 
        category_id,
        category_name,
        parent_category_id,
        is_active
    from {{ source('dwh_raw', 'categories') }}
),

parent_categories as (
    select 
        parent_cat.category_id as parent_category_id,
        trim(initcap(parent_cat.category_name)) as parent_category_name
    from {{ source('dwh_raw', 'categories') }} parent_cat
),

final_categories as (
    select 
        src_cat.category_id,
        trim(initcap(src_cat.category_name)) as category_name,
        src_cat.parent_category_id,
        case 
            when src_cat.parent_category_id is not null and parent_cat.parent_category_name is not null
            then parent_cat.parent_category_name || ' > ' || trim(initcap(src_cat.category_name))
            else trim(initcap(src_cat.category_name))
        end as category_path,
        coalesce(src_cat.is_active, true) as is_active
    from source_categories src_cat
    left join parent_categories parent_cat
        on src_cat.parent_category_id = parent_cat.parent_category_id
)

select 
    category_id,
    category_name,
    parent_category_id,
    category_path,
    is_active
from final_categories