{#
------------------------------------------------------------------------
MODEL NAME    : dim_address
TARGET TABLE  : BSL_MA.DWH_MA.DIM_ADDRESS
SOURCE TABLES : BSL_RAW.DWH_RAW.ADDRESSES, BSL_MA.DWH_MA.DIM_CUSTOMER
DESCRIPTION   : Dimension table for address information with customer 
                lookup and data transformations including trimming and 
                uppercase city names
PREREQUISITES : dim_customer table must exist for customer_id lookup
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2025-11-27
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table'
) }}

WITH source_addresses AS (
    SELECT
        address_id,
        customer_id,
        address_line1,
        city,
        country,
        inserted_at
    FROM {{ source('dwh_raw', 'addresses') }}
),

customer_lookup AS (
    SELECT
        customer_id
    FROM {{ ref('dim_customer') }}
),

validated_addresses AS (
    SELECT
        source_addresses.address_id,
        source_addresses.customer_id,
        source_addresses.address_line1,
        source_addresses.city,
        source_addresses.country,
        source_addresses.inserted_at
    FROM source_addresses
    INNER JOIN customer_lookup
        ON source_addresses.customer_id = customer_lookup.customer_id
),

transformed AS (
    SELECT
        address_id,
        customer_id,
        TRIM(address_line1) AS address_line1,
        UPPER(city) AS city,
        country,
        inserted_at AS last_updated -- auto corrected using semantic file
    FROM validated_addresses
)

SELECT * FROM transformed