{#
------------------------------------------------------------------------
MODEL NAME    : dim_supplier
TARGET TABLE  : bsl_ma.dwh_ma.dim_supplier
SOURCE TABLES : bsl_raw.dwh_raw.suppliers
DESCRIPTION   : Dimension table for suppliers with data quality transformations
                including email validation, name formatting, and default values
PREREQUISITES : Source table bsl_raw.dwh_raw.suppliers must exist
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2025-11-17
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_suppliers as (
    select
        supplier_id,
        supplier_name,
        contact_email,
        country,
        active_flag
    from {{ source('dwh_raw', 'suppliers') }}
),

transformed_suppliers as (
    select
        -- Direct mapping for supplier_id
        source_suppliers.supplier_id as supplier_id,
        
        -- Trim and title-case for supplier_name
        initcap(trim(source_suppliers.supplier_name)) as supplier_name,
        
        -- Lowercase email with validation - set null if invalid pattern
        case 
            when source_suppliers.contact_email is not null 
                 and regexp_like(source_suppliers.contact_email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')
            then lower(source_suppliers.contact_email)
            else null
        end as contact_email,
        
        -- Uppercase country
        upper(source_suppliers.country) as country,
        
        -- Direct mapping for active_flag with default false if null
        coalesce(source_suppliers.active_flag, false) as is_active
        
    from source_suppliers
)

select
    supplier_id,
    supplier_name,
    contact_email,
    country,
    is_active
from transformed_suppliers