{#
------------------------------------------------------------------------
MODEL NAME    : dim_supplier
TARGET TABLE  : BSL_MA.DWH_MA.DIM_SUPPLIER
SOURCE TABLES : BSL_RAW.DWH_RAW.SUPPLIERS
DESCRIPTION   : Dimension table for suppliers containing supplier details
                with data transformations including name formatting, email
                validation, and country standardization
PREREQUISITES : Source table BSL_RAW.DWH_RAW.SUPPLIERS must exist
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-27
------------------------------------------------------------------------
#}

{{ config(
    materialized='table',
    unique_key='supplier_id',
    incremental_strategy='merge'
) }}

WITH source_data AS (
    SELECT
        supplier_id,
        supplier_name,
        contact_email,
        country,
        active_flag,
        inserted_at
    FROM {{ source('dwh_raw', 'suppliers') }}
    {% if var('backfill_flag') == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("backfill_start_date") }}' AND '{{ var("backfill_end_date") }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > COALESCE((SELECT MAX(last_updated) FROM BSL_MA.DWH_MA.dim_supplier), TO_DATE('0001-01-01'))
        {% endif %}
    {% endif %}
),

transformed AS (
    SELECT
        supplier_id,
        INITCAP(TRIM(supplier_name)) AS supplier_name, -- Trim and title-case
        CASE 
            WHEN REGEXP_LIKE(contact_email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$') 
            THEN LOWER(contact_email) -- Lowercase email
            ELSE NULL -- auto corrected using semantic file: If invalid email pattern set null
        END AS contact_email,
        UPPER(country) AS country, -- Uppercase country
        COALESCE(active_flag, FALSE) AS is_active, -- auto corrected using semantic file: If null default false
        inserted_at AS last_updated -- Direct mapping
    FROM source_data
)

SELECT * FROM transformed