{#
------------------------------------------------------------------------
MODEL NAME    : dim_supplier
TARGET TABLE  : BSL_MA.DWH_MA.DIM_SUPPLIER
SOURCE TABLES : BSL_RAW.DWH_RAW.SUPPLIERS
DESCRIPTION   : This model creates a dimension table for suppliers with 
                cleaned and transformed data including proper casing,
                email validation, and default values for missing data.
PREREQUISITES : Source table SUPPLIERS must exist in BSL_RAW.DWH_RAW
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-25
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_supplier'
) }}

WITH source_data AS (
    SELECT
        supplier_id,
        supplier_name,
        contact_email,
        country,
        active_flag,
        inserted_at
    FROM {{ source('dwh_raw', 'suppliers') }}
    {% if var('models')['backfill_flag'] == 'true' %}
        WHERE inserted_at BETWEEN 'var("models")["backfill_start_date"]' AND 'var("models")["backfill_end_date"]'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > (SELECT MAX(inserted_at) FROM {{ this }})
        {% endif %}
    {% endif %}
),

transformed AS (
    SELECT
        supplier_id, -- Direct mapping
        INITCAP(TRIM(supplier_name)) AS supplier_name, -- Trim and title-case
        CASE 
            WHEN REGEXP_LIKE(contact_email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$') 
            THEN LOWER(contact_email) 
            ELSE NULL 
        END AS contact_email, -- Lowercase email, auto corrected using semantic file
        UPPER(country) AS country, -- Uppercase country
        COALESCE(active_flag, FALSE) AS is_active, -- Direct mapping with default false for null, auto corrected using semantic file
        inserted_at AS last_updated -- Direct mapping, auto corrected using semantic file
    FROM source_data
)

SELECT * FROM transformed