{#
------------------------------------------------------------------------
MODEL NAME    : dim_product
TARGET TABLE  : bsl_ma.dwh_ma.dim_product
SOURCE TABLES : bsl_raw.dwh_raw.products
DESCRIPTION   : Dimension table for products with transformed price bands
                and standardized product names
PREREQUISITES : Source table bsl_raw.dwh_raw.products must exist
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2025-11-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

with source_products as (
    select
        product_id,
        product_name,
        price
    from {{ source('dwh_raw', 'products') }}
),

transformed_products as (
    select
        source_products.product_id,
        
        -- Transform product name to title case and trim spaces
        trim(initcap(source_products.product_name)) as product_name,
        
        -- Direct mapping for price with precision
        cast(source_products.price as number(10,2)) as price,
        
        -- Create price band based on price ranges
        case
            when source_products.price < 50 then 'Low'
            when source_products.price >= 50 and source_products.price <= 199.99 then 'Mid'
            when source_products.price >= 200 and source_products.price <= 499.99 then 'High'
            when source_products.price >= 500 then 'Premium'
            else 'Unknown'
        end as price_band,
        
        -- Add notes for zero price items
        case
            when source_products.price = 0 then 'Price is zero - flagged for review'
            else null
        end as review_notes
        
    from source_products
)

select * from transformed_products