{#
------------------------------------------------------------------------
MODEL NAME    : dim_address
TARGET TABLE  : BSL_MA.DWH_MA.DIM_ADDRESS
SOURCE TABLES : BSL_RAW.DWH_RAW.ADDRESSES
DESCRIPTION   : Dimension table for address information with customer 
                lookup and data transformations including trimming 
                whitespace and uppercasing city names
PREREQUISITES : dim_customer table must exist for customer_id lookup
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-25
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_address'
) }}

WITH source_data AS (
    SELECT
        address_id,
        customer_id,
        address_line1,
        city,
        country,
        inserted_at
    FROM {{ source('dwh_raw', 'addresses') }}
    {% if var('models')['backfill_flag'] == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("models")["backfill_start_date"] }}' AND '{{ var("models")["backfill_end_date"] }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > (SELECT MAX(inserted_at) FROM {{ this }})
        {% endif %}
    {% endif %}
),

customer_lookup AS (
    SELECT
        customer_id
    FROM {{ ref('dim_customer') }}
),

validated_addresses AS (
    SELECT
        source_addresses.address_id,
        source_addresses.customer_id,
        source_addresses.address_line1,
        source_addresses.city,
        source_addresses.country,
        source_addresses.inserted_at
    FROM source_data AS source_addresses
    INNER JOIN customer_lookup AS customers
        ON source_addresses.customer_id = customers.customer_id
),

transformed AS (
    SELECT
        address_id,
        customer_id,
        TRIM(address_line1) AS address_line1,
        UPPER(city) AS city,
        country,
        inserted_at AS last_updated -- auto corrected using semantic file
    FROM validated_addresses
)

SELECT * FROM transformed