{#
------------------------------------------------------------------------
MODEL NAME    : dim_category
TARGET TABLE  : bsl_ma.dwh_ma.dim_category
SOURCE TABLES : bsl_raw.dwh_raw.categories
DESCRIPTION   : Dimension table for product categories with hierarchical 
                path structure up to 2 levels
PREREQUISITES : Source table categories must be available in dwh_raw schema
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2025-11-18
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_categories as (
    select
        category_id,
        category_name,
        parent_category_id,
        is_active
    from {{ source('dwh_raw', 'categories') }}
),

parent_categories as (
    select
        category_id as parent_id,
        category_name as parent_name
    from {{ source('dwh_raw', 'categories') }}
),

transformed_categories as (
    select
        src.category_id,
        trim(initcap(src.category_name)) as category_name,
        src.parent_category_id,
        case 
            when src.parent_category_id is not null and parent.parent_name is not null
            then trim(initcap(parent.parent_name)) || ' > ' || trim(initcap(src.category_name))
            else trim(initcap(src.category_name))
        end as category_path,
        coalesce(src.is_active, true) as is_active
    from source_categories src
    left join parent_categories parent
        on src.parent_category_id = parent.parent_id
)

select
    category_id,
    category_name,
    parent_category_id,
    category_path,
    is_active
from transformed_categories