{#
------------------------------------------------------------------------
MODEL NAME    : dim_customer
TARGET TABLE  : BSL_MA.DWH_MA.DIM_CUSTOMER
SOURCE TABLES : BSL_RAW.DWH_RAW.CUSTOMERS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : Customer dimension table with customer details, tier classification
                based on spending patterns, and data quality transformations
PREREQUISITES : Source tables CUSTOMERS and ORDERS must be available
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-27
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'view',
    unique_key = 'customer_id',
    incremental_strategy = 'merge'
) }}

WITH source_customers AS (
    SELECT
        customer_id,
        first_name, -- auto corrected using semantic file
        last_name, -- auto corrected using semantic file
        email,
        created_at,
        inserted_at
    FROM {{ source('dwh_raw', 'customers') }}
    {% if var('backfill_flag') == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("backfill_start_date") }}' AND '{{ var("backfill_end_date") }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > COALESCE(
                (SELECT MAX(last_updated) FROM BSL_MA.DWH_MA.dim_customer), 
                TO_DATE('0001-01-01')
            )
        {% endif %}
    {% endif %}
),

source_orders AS (
    SELECT
        customer_id,
        total_amount,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
    WHERE order_date >= DATEADD(day, -365, CURRENT_DATE())
),

customer_spending AS (
    SELECT
        orders.customer_id,
        SUM(orders.total_amount) AS total_spending_365_days
    FROM source_orders AS orders
    GROUP BY orders.customer_id
),

transformed AS (
    SELECT
        customers.customer_id,
        UPPER(TRIM(customers.first_name)) AS first_name,
        UPPER(TRIM(customers.last_name)) AS last_name,
        CASE 
            WHEN customers.email REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' 
            THEN LOWER(customers.email)
            ELSE NULL
        END AS email,
        customers.created_at::DATE AS customer_since_date,
        CASE 
            WHEN COALESCE(spending.total_spending_365_days, 0) >= 1000 THEN 'Gold'
            WHEN COALESCE(spending.total_spending_365_days, 0) >= 500 THEN 'Silver'
            ELSE 'Bronze'
        END AS customer_tier,
        COALESCE(customers.inserted_at, CURRENT_DATE()) AS last_updated
    FROM source_customers AS customers
    LEFT JOIN customer_spending AS spending
        ON customers.customer_id = spending.customer_id
)

SELECT * FROM transformed