{#
------------------------------------------------------------------------
MODEL NAME    : dim_product
TARGET TABLE  : BSL_MA.DWH_MA.DIM_PRODUCT
SOURCE TABLES : BSL_RAW.DWH_RAW.PRODUCTS
DESCRIPTION   : Dimension table for products with price banding and 
                standardized product names
PREREQUISITES : Source table PRODUCTS must exist in BSL_RAW.DWH_RAW
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2025-11-20
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_products as (
    select 
        products.product_id,
        products.product_name,
        products.price,
        products.category_id, -- auto corrected using semantic file
        products.inserted_at
    from {{ source('dwh_raw', 'products') }} as products
),

transformed_products as (
    select
        source_products.product_id,
        
        -- Title-case product name and trim excessive spaces
        initcap(trim(regexp_replace(source_products.product_name, '\\s+', ' '))) as product_name,
        
        -- Direct mapping for price
        source_products.price,
        
        -- Price banding logic
        case 
            when source_products.price < 50 then 'Low'
            when source_products.price >= 50 and source_products.price <= 199.99 then 'Mid'
            when source_products.price >= 200 and source_products.price <= 499.99 then 'High'
            when source_products.price >= 500 then 'Premium'
            else 'Unknown'
        end as price_band,
        
        source_products.category_id,
        source_products.inserted_at
        
    from source_products
)

select 
    transformed_products.product_id,
    transformed_products.product_name,
    transformed_products.price,
    transformed_products.price_band,
    transformed_products.category_id,
    transformed_products.inserted_at
from transformed_products