{#
------------------------------------------------------------------------
MODEL NAME    : dim_customer
TARGET TABLE  : bsl_ma.dwh_ma.dim_customer
SOURCE TABLES : bsl_raw.dwh_raw.customers, bsl_raw.dwh_raw.orders
DESCRIPTION   : Customer dimension table with derived customer tier based on
                spending patterns in the last 365 days
PREREQUISITES : Source tables customers and orders must be available
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2025-11-17
------------------------------------------------------------------------
#}

with customers_base as (
    select
        customer_id,
        first_name,
        last_name,
        email,
        inserted_at
    from {{ source('dwh_raw', 'customers') }}
),

orders_base as (
    select
        customer_id,
        total_amount,
        order_date
    from {{ source('dwh_raw', 'orders') }}
    where order_date >= current_date - 365
),

customer_spending as (
    select
        orders.customer_id,
        sum(orders.total_amount) as total_spending_365_days
    from orders_base as orders
    group by orders.customer_id
),

final as (
    select
        customers.customer_id,
        trim(upper(customers.first_name)) as first_name,
        trim(upper(customers.last_name)) as last_name,
        case
            when customers.email rlike '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
            then lower(customers.email)
            else null
        end as email,
        case
            when customers.inserted_at is null
            then current_date
            else customers.inserted_at::date
        end as customer_since_date,
        case
            when coalesce(spending.total_spending_365_days, 0) >= 1000 then 'Gold'
            when coalesce(spending.total_spending_365_days, 0) >= 500 then 'Silver'
            else 'Bronze'
        end as customer_tier
    from customers_base as customers
    left join customer_spending as spending
        on customers.customer_id = spending.customer_id
)

select * from final