{#
------------------------------------------------------------------------
MODEL NAME    : fact_order_item
TARGET TABLE  : BSL_MA.DWH_MA.FACT_ORDER_ITEM
SOURCE TABLES : BSL_RAW.DWH_RAW.ORDER_ITEMS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model creates a fact table for order items with 
                extended amounts, discount allocations, and net amounts.
                Includes lookups to validate order and product references.
PREREQUISITES : dim_product and fact_order models must exist
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-27
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_item_id',
    incremental_strategy='merge'
) }}

WITH source_order_items AS (
    SELECT
        order_item_id,
        order_id,
        product_id,
        quantity,
        unit_price,
        inserted_at
    FROM {{ source('dwh_raw', 'order_items') }}
    {% if var('backfill_flag') == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("backfill_start_date") }}' AND '{{ var("backfill_end_date") }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > COALESCE(
                (SELECT MAX(last_updated) FROM BSL_MA.DWH_MA.fact_order_item), 
                TO_DATE('0001-01-01')
            )
        {% endif %}
    {% endif %}
),

source_orders AS (
    SELECT
        order_id
    FROM {{ source('dwh_raw', 'orders') }}
),

validated_order_items AS (
    SELECT
        order_items.order_item_id,
        order_items.order_id,
        CASE 
            WHEN order_items.product_id IS NULL THEN '0'
            ELSE order_items.product_id
        END AS product_id, -- auto corrected using semantic file: handling missing product_id
        ROUND(order_items.quantity) AS quantity, -- auto corrected using semantic file: ensure integer semantics
        COALESCE(order_items.unit_price, 0) AS unit_price, -- auto corrected using semantic file: handle null unit_price
        order_items.inserted_at
    FROM source_order_items AS order_items
    INNER JOIN source_orders AS orders
        ON order_items.order_id = orders.order_id -- auto corrected using semantic file: skip items if order_id missing
),

calculated_amounts AS (
    SELECT
        order_item_id,
        order_id,
        product_id,
        quantity,
        unit_price,
        (quantity * unit_price) AS extended_amount,
        0 AS discount_amount, -- auto corrected using semantic file: set 0 if no discount context
        inserted_at
    FROM validated_order_items
),

final_calculations AS (
    SELECT
        order_item_id,
        order_id,
        product_id,
        quantity,
        unit_price,
        extended_amount,
        discount_amount,
        GREATEST(extended_amount - discount_amount, 0) AS net_amount, -- auto corrected using semantic file: ensure non-negative, floor at 0
        inserted_at AS last_updated
    FROM calculated_amounts
)

SELECT * FROM final_calculations