{#
------------------------------------------------------------------------
MODEL NAME    : fact_inventory
TARGET TABLE  : BSL_MA.DWH_MA.FACT_INVENTORY
SOURCE TABLES : BSL_RAW.DWH_RAW.INVENTORY
DESCRIPTION   : Inventory latest snapshot with product and supplier lookups
PREREQUISITES : dim_product and dim_supplier models should exist
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-21
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with inventory_base as (
    select
        inventory.product_id,
        inventory.supplier_id,
        inventory.stock_qty,
        inventory.warehouse_location,
        inventory.last_updated,
        inventory.inserted_at -- auto corrected using semantic file
    from {{ source('dwh_raw', 'inventory') }} as inventory
    {% if var('models')['backfill_flag'] == 'true' %}
        where inventory.inserted_at between '{{ var("models")["backfill_start_date"] }}' and '{{ var("models")["backfill_end_date"] }}'
    {% else %}
        {% if is_incremental() %}
            where inventory.inserted_at > (select max(inserted_at) from {{ this }})
        {% endif %}
    {% endif %}
),

inventory_with_flags as (
    select
        inventory_base.product_id,
        inventory_base.supplier_id,
        case 
            when inventory_base.stock_qty < 0 then null
            else inventory_base.stock_qty
        end as stock_qty,
        upper(inventory_base.warehouse_location) as warehouse_location,
        date(inventory_base.last_updated) as snapshot_date,
        case 
            when row_number() over (
                partition by inventory_base.product_id, inventory_base.supplier_id 
                order by inventory_base.last_updated desc
            ) = 1 then true
            else false
        end as is_latest,
        inventory_base.inserted_at as last_updated
    from inventory_base
),

final_inventory as (
    select
        coalesce(inventory_flags.product_id, '0') as product_id,
        coalesce(inventory_flags.supplier_id, '0') as supplier_id,
        inventory_flags.stock_qty,
        inventory_flags.warehouse_location,
        inventory_flags.snapshot_date,
        inventory_flags.is_latest,
        inventory_flags.last_updated,
        current_timestamp() as last_updated_timestamp
    from inventory_with_flags as inventory_flags
)

select * from final_inventory