{#
------------------------------------------------------------------------
MODEL NAME    : fact_shipment
TARGET TABLE  : BSL_MA.DWH_MA.FACT_SHIPMENT
SOURCE TABLES : BSL_RAW.DWH_RAW.SHIPMENTS, BSL_MA.DWH_MA.FACT_ORDER
DESCRIPTION   : Fact table for shipment data with order lookup and 
                calculated days to ship metrics
PREREQUISITES : fact_order model must exist and be populated
PARAMETER     : Incremental load based on last_updated timestamp
AUTHOUR       : AI Generated by Shajahan - 2025-11-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='shipment_id'
) }}

with source_shipments as (
    select 
        shipment_id,
        order_id,
        shipped_date,
        carrier,
        tracking_number
    from {{ source('dwh_raw', 'shipments') }}
    {% if is_incremental() %}
        where shipped_date > (select max(shipped_date) from {{ this }})
    {% endif %}
),

fact_orders as (
    select 
        order_id,
        order_date
    from {{ ref('fact_order') }}
),

shipment_with_order_data as (
    select 
        shipments.shipment_id,
        shipments.order_id,
        shipments.shipped_date::date as shipped_date,
        orders.order_date,
        upper(shipments.carrier) as carrier,
        shipments.tracking_number
    from source_shipments as shipments
    inner join fact_orders as orders
        on shipments.order_id = orders.order_id
),

final as (
    select 
        shipment_id,
        order_id,
        shipped_date,
        greatest(0, datediff('day', order_date::date, shipped_date)) as days_to_ship,
        carrier,
        tracking_number,
        current_timestamp() as last_updated
    from shipment_with_order_data
)

select * from final