{#
------------------------------------------------------------------------
MODEL NAME    : fact_shipment
TARGET TABLE  : BSL_MA.DWH_MA.FACT_SHIPMENT
SOURCE TABLES : BSL_RAW.DWH_RAW.SHIPMENTS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model creates a fact table for shipments with 
                calculated days to ship and transformed data from 
                shipments and orders tables
PREREQUISITES : Source tables shipments and orders must be available
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-21
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='shipment_id'
) }}

with shipments_source as (
    select
        shipments.shipment_id,
        shipments.order_id,
        shipments.shipped_date,
        shipments.carrier,
        shipments.tracking_number,
        shipments.inserted_at -- auto corrected using semantic file
    from {{ source('dwh_raw', 'shipments') }} as shipments
    {% if var('models')['backfill_flag'] == 'true' %}
        where shipments.inserted_at between '{{ var("models")["backfill_start_date"] }}' and '{{ var("models")["backfill_end_date"] }}'
    {% else %}
        {% if is_incremental() %}
            where shipments.inserted_at > (select max(inserted_at) from {{ this }})
        {% endif %}
    {% endif %}
),

orders_source as (
    select
        orders.order_id,
        orders.order_date
    from {{ source('dwh_raw', 'orders') }} as orders
),

shipments_with_orders as (
    select
        shipments_source.shipment_id,
        shipments_source.order_id,
        shipments_source.shipped_date::date as shipped_date,
        shipments_source.carrier,
        shipments_source.tracking_number,
        shipments_source.inserted_at,
        orders_source.order_date
    from shipments_source
    inner join orders_source
        on shipments_source.order_id = orders_source.order_id
),

final_shipments as (
    select
        shipments_with_orders.shipment_id,
        shipments_with_orders.order_id,
        shipments_with_orders.shipped_date,
        greatest(0, datediff('day', shipments_with_orders.order_date::date, shipments_with_orders.shipped_date)) as days_to_ship,
        upper(shipments_with_orders.carrier) as carrier,
        shipments_with_orders.tracking_number,
        current_timestamp() as last_updated
    from shipments_with_orders
)

select * from final_shipments