{#
------------------------------------------------------------------------
MODEL NAME    : fact_order
TARGET TABLE  : BSL_MA.DWH_MA.FACT_ORDER
SOURCE TABLES : BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model creates a fact table for orders with customer 
                lookups, status normalization, and data type conversions.
                Includes incremental loading with backfill support.
PREREQUISITES : dim_customer table must exist for customer lookups
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-27
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id',
    incremental_strategy='merge'
) }}

WITH source_data AS (
    SELECT
        orders.order_id,
        orders.customer_id,
        orders.order_date,
        orders.status,
        orders.total_amount,
        orders.inserted_at
    FROM {{ source('dwh_raw', 'orders') }} AS orders
    {% if var('backfill_flag') == 'true' %}
        WHERE orders.inserted_at BETWEEN '{{ var("backfill_start_date") }}' AND '{{ var("backfill_end_date") }}'
    {% else %}
        {% if is_incremental() %}
            WHERE orders.inserted_at > COALESCE(
                (SELECT MAX(last_updated) FROM BSL_MA.DWH_MA.fact_order), 
                TO_DATE('0001-01-01')
            )
        {% endif %}
    {% endif %}
),

customer_lookup AS (
    SELECT
        customer_id
    FROM {{ ref('dim_customer') }}
),

validated_orders AS (
    SELECT
        source_data.order_id,
        source_data.customer_id,
        DATE(source_data.order_date) AS order_date, -- auto corrected using semantic file
        CASE 
            WHEN UPPER(source_data.status) IN ('PENDING', 'CANCELLED', 'SHIPPED', 'DELIVERED') 
            THEN UPPER(source_data.status)
            ELSE 'PENDING'
        END AS order_status,
        CASE 
            WHEN source_data.total_amount < 0 
            THEN NULL 
            ELSE source_data.total_amount 
        END AS total_amount,
        source_data.inserted_at AS last_updated
    FROM source_data
    INNER JOIN customer_lookup 
        ON source_data.customer_id = customer_lookup.customer_id
)

SELECT * FROM validated_orders