{#
------------------------------------------------------------------------
MODEL NAME    : fact_order
TARGET TABLE  : BSL_MA.DWH_MA.FACT_ORDER
SOURCE TABLES : BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model transforms raw order data into a business-ready 
                fact table with proper data type conversions, status 
                normalization, and customer validation
PREREQUISITES : dim_customer table must exist for customer lookup validation
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-25
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    alias='fact_order'
) }}

WITH source_data AS (
    SELECT
        order_id,
        customer_id,
        order_date,
        status,
        total_amount,
        inserted_at
    FROM {{ source('dwh_raw', 'orders') }}
    {% if var('models')['backfill_flag'] == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("models")["backfill_start_date"] }}' AND '{{ var("models")["backfill_end_date"] }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > (SELECT MAX(inserted_at) FROM {{ this }})
        {% endif %}
    {% endif %}
),

customer_validation AS (
    SELECT
        source_orders.order_id,
        source_orders.customer_id,
        source_orders.order_date,
        source_orders.status,
        source_orders.total_amount,
        source_orders.inserted_at
    FROM source_data AS source_orders
    INNER JOIN {{ ref('dim_customer') }} AS dim_customers
        ON source_orders.customer_id = dim_customers.customer_id
),

transformed AS (
    SELECT
        order_id,
        customer_id,
        DATE(order_date) AS order_date, -- Convert timestamp to date
        CASE 
            WHEN UPPER(status) IN ('PENDING', 'CANCELLED', 'SHIPPED', 'DELIVERED') 
            THEN UPPER(status)
            ELSE 'PENDING' -- If value outside list set to 'PENDING'
        END AS order_status,
        CASE 
            WHEN total_amount < 0 THEN NULL -- If negative set to null and log
            ELSE total_amount
        END AS total_amount,
        inserted_at AS last_updated
    FROM customer_validation
)

SELECT * FROM transformed