{#
------------------------------------------------------------------------
MODEL NAME    : fact_order
TARGET TABLE  : bsl_ma.dwh_ma.fact_order
SOURCE TABLES : bsl_raw.dwh_raw.orders
DESCRIPTION   : Fact table for order data with normalized status values,
                date conversions, and customer lookups. Includes data
                quality checks and incremental processing.
PREREQUISITES : dim_customer table must exist for customer lookups
PARAMETER     : Incremental materialization with last_updated tracking
AUTHOR        : AI Generated by Shajahan - 2025-11-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

with source_orders as (
    select
        order_id,
        customer_id,
        order_date,
        status,
        total_amount
    from {{ source('dwh_raw', 'orders') }}
    {% if is_incremental() %}
        where last_updated > (select max(last_updated) from {{ this }})
    {% endif %}
),

customer_lookup as (
    select
        customer_id
    from {{ ref('dim_customer') }}
),

transformed_orders as (
    select
        source_orders.order_id,
        source_orders.customer_id,
        date(source_orders.order_date) as order_date,
        case
            when upper(source_orders.status) in ('PENDING', 'CANCELLED', 'SHIPPED', 'DELIVERED')
            then upper(source_orders.status)
            else 'PENDING'
        end as order_status,
        case
            when source_orders.total_amount < 0
            then null
            else source_orders.total_amount
        end as total_amount,
        current_timestamp() as last_updated
    from source_orders
    inner join customer_lookup
        on source_orders.customer_id = customer_lookup.customer_id
)

select
    order_id,
    customer_id,
    order_date,
    order_status,
    total_amount,
    last_updated
from transformed_orders