{#
------------------------------------------------------------------------
MODEL NAME    : fact_payment
TARGET TABLE  : BSL_MA.DWH_MA.FACT_PAYMENT
SOURCE TABLES : BSL_RAW.DWH_RAW.PAYMENTS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model transforms payment data from raw layer to create
                a comprehensive fact table for payment analytics. It includes
                payment details, order validation, and payment status flags.
PREREQUISITES : Orders data must be available in fact_order table
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-25
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    alias = 'fact_payment'
) }}

WITH source_payments AS (
    SELECT
        payment_id,
        order_id,
        payment_date,
        payment_method,
        amount,
        inserted_at
    FROM {{ source('dwh_raw', 'payments') }}
    {% if var('models')['backfill_flag'] == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("models")["backfill_start_date"] }}' AND '{{ var("models")["backfill_end_date"] }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > (SELECT MAX(inserted_at) FROM {{ this }})
        {% endif %}
    {% endif %}
),

source_orders AS (
    SELECT
        order_id,
        total_amount
    FROM {{ source('dwh_raw', 'orders') }}
),

validated_payments AS (
    SELECT
        payments.payment_id,
        payments.order_id,
        payments.payment_date::DATE AS payment_date, -- auto corrected using semantic file
        CASE 
            WHEN UPPER(payments.payment_method) IN ('CREDIT CARD', 'DEBIT CARD') THEN 'CARD'
            WHEN UPPER(payments.payment_method) = 'PAYPAL' THEN 'UPI'
            WHEN UPPER(payments.payment_method) IN ('COD', 'CASH ON DELIVERY') THEN 'COD'
            WHEN UPPER(payments.payment_method) IN ('NET BANKING', 'NETBANKING') THEN 'NETBANKING'
            ELSE 'CARD'
        END AS payment_method,
        CASE 
            WHEN payments.amount < 0 THEN NULL
            ELSE payments.amount
        END AS amount,
        orders.total_amount AS order_total_amount,
        payments.inserted_at AS last_updated -- auto corrected using semantic file
    FROM source_payments AS payments
    INNER JOIN source_orders AS orders
        ON payments.order_id = orders.order_id
),

payment_aggregation AS (
    SELECT
        order_id,
        SUM(COALESCE(amount, 0)) AS total_payments
    FROM validated_payments
    GROUP BY order_id
),

transformed AS (
    SELECT
        payments.payment_id,
        payments.order_id,
        payments.payment_date,
        payments.payment_method,
        payments.amount,
        CASE 
            WHEN payments.order_total_amount IS NULL THEN FALSE
            WHEN agg.total_payments >= payments.order_total_amount THEN TRUE
            ELSE FALSE
        END AS is_fully_applied,
        payments.last_updated
    FROM validated_payments AS payments
    LEFT JOIN payment_aggregation AS agg
        ON payments.order_id = agg.order_id
)

SELECT * FROM transformed