{#
------------------------------------------------------------------------
MODEL NAME    : fact_payment
TARGET TABLE  : BSL_MA.DWH_MA.FACT_PAYMENT
SOURCE TABLES : BSL_RAW.DWH_RAW.PAYMENTS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model creates a fact table for payment transactions with 
                payment details, order references, and payment status flags.
                Includes data quality transformations and business logic.
PREREQUISITES : Source tables payments and orders must exist with valid data
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-25
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    alias = 'fact_payment'
) }}

WITH payments_source AS (
    SELECT
        payment_id,
        order_id,
        payment_date,
        payment_method,
        amount,
        inserted_at
    FROM {{ source('dwh_raw', 'payments') }}
    {% if var('models')['backfill_flag'] == 'true' %}
        WHERE inserted_at BETWEEN '{{ var("models")["backfill_start_date"] }}' AND '{{ var("models")["backfill_end_date"] }}'
    {% else %}
        {% if is_incremental() %}
            WHERE inserted_at > (SELECT MAX(inserted_at) FROM {{ this }})
        {% endif %}
    {% endif %}
),

orders_source AS (
    SELECT
        order_id,
        total_amount
    FROM {{ source('dwh_raw', 'orders') }}
),

payment_order_joined AS (
    SELECT
        payments.payment_id,
        payments.order_id,
        payments.payment_date,
        payments.payment_method,
        payments.amount,
        payments.inserted_at,
        orders.total_amount AS order_total_amount
    FROM payments_source AS payments
    LEFT JOIN orders_source AS orders
        ON payments.order_id = orders.order_id
    WHERE orders.order_id IS NOT NULL  -- Skip payment if order not present
),

payment_aggregated AS (
    SELECT
        order_id,
        SUM(amount) AS total_payments_for_order
    FROM payment_order_joined
    GROUP BY order_id
),

transformed AS (
    SELECT
        payments.payment_id,
        payments.order_id,
        DATE(payments.payment_date) AS payment_date,  -- Convert timestamp to date
        CASE 
            WHEN UPPER(payments.payment_method) IN ('CREDIT CARD', 'DEBIT CARD') THEN 'CARD'
            WHEN UPPER(payments.payment_method) = 'PAYPAL' THEN 'UPI'  -- auto corrected using semantic file
            ELSE 'CARD'  -- If not in list set to 'CARD'
        END AS payment_method,
        CASE 
            WHEN payments.amount < 0 THEN NULL  -- If negative set to null and log
            ELSE payments.amount
        END AS amount,
        CASE 
            WHEN payments.order_total_amount IS NULL THEN FALSE  -- If order total null set false
            WHEN agg.total_payments_for_order >= payments.order_total_amount THEN TRUE
            ELSE FALSE
        END AS is_fully_applied,
        payments.inserted_at AS last_updated,  -- Direct mapping
        CURRENT_TIMESTAMP() AS last_updated  -- auto corrected using semantic file
    FROM payment_order_joined AS payments
    LEFT JOIN payment_aggregated AS agg
        ON payments.order_id = agg.order_id
)

SELECT * FROM transformed