{#
------------------------------------------------------------------------
MODEL NAME    : fact_inventory
TARGET TABLE  : BSL_MA.DWH_MA.FACT_INVENTORY
SOURCE TABLES : BSL_RAW.DWH_RAW.INVENTORY
DESCRIPTION   : Inventory latest snapshot with product and supplier lookups,
                including latest record flags and data quality handling
PREREQUISITES : dim_product and dim_supplier models should exist
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2025-11-27
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'fact_inventory'
) }}

WITH source_data AS (
    SELECT
        inventory.product_id,
        inventory.supplier_id,
        inventory.stock_qty,
        inventory.warehouse_location,
        inventory.last_updated,
        inventory.inserted_at
    FROM {{ source('dwh_raw', 'inventory') }} AS inventory
),

transformed AS (
    SELECT
        -- Product lookup with unknown handling
        COALESCE(inventory.product_id, '0') AS product_id, -- auto corrected using semantic file
        
        -- Supplier lookup with unknown handling  
        COALESCE(inventory.supplier_id, '0') AS supplier_id, -- auto corrected using semantic file
        
        -- Stock quantity with negative value handling
        CASE 
            WHEN inventory.stock_qty < 0 THEN NULL 
            ELSE inventory.stock_qty 
        END AS stock_qty,
        
        -- Warehouse location uppercase transformation
        UPPER(inventory.warehouse_location) AS warehouse_location,
        
        -- Convert timestamp to date for snapshot
        DATE(inventory.last_updated) AS snapshot_date, -- auto corrected using semantic file
        
        -- Flag latest record per product_id + supplier_id combination
        CASE 
            WHEN inventory.last_updated = MAX(inventory.last_updated) OVER (
                PARTITION BY inventory.product_id, inventory.supplier_id
            ) THEN TRUE 
            ELSE FALSE 
        END AS is_latest,
        
        -- Direct mapping for last_updated
        inventory.inserted_at AS last_updated -- auto corrected using semantic file
        
    FROM source_data AS inventory
)

SELECT * FROM transformed