{#
------------------------------------------------------------------------
MODEL NAME    : fact_payment
TARGET TABLE  : bsl_ma.dwh_ma.fact_payment
SOURCE TABLES : bsl_raw.dwh_raw.payments, bsl_raw.dwh_raw.orders
DESCRIPTION   : Fact table for payment transactions with order validation
                and payment method standardization. Includes incremental
                loading capability with last_updated tracking.
PREREQUISITES : fact_order model must exist for order validation
PARAMETER     : Incremental materialization based on last_updated column
AUTHOUR       : AI Generated by Shajahan - 2025-11-18
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='payment_id'
) }}

with source_payments as (
    select
        payment_id,
        order_id,
        payment_date,
        payment_method,
        amount
    from {{ source('dwh_raw', 'payments') }}
    {% if is_incremental() %}
        where payment_date > (select max(last_updated) from {{ this }})
    {% endif %}
),

source_orders as (
    select
        order_id,
        total_amount
    from {{ source('dwh_raw', 'orders') }}
),

validated_payments as (
    select
        payments.payment_id,
        payments.order_id,
        payments.payment_date::date as payment_date,
        case
            when upper(payments.payment_method) in ('CARD', 'UPI', 'COD', 'NETBANKING')
            then upper(payments.payment_method)
            else 'CARD'
        end as payment_method,
        case
            when payments.amount < 0 then null
            else payments.amount
        end as amount,
        orders.total_amount as order_total_amount
    from source_payments as payments
    inner join source_orders as orders
        on payments.order_id = orders.order_id
),

payment_aggregation as (
    select
        order_id,
        sum(amount) as total_payments
    from validated_payments
    group by order_id
),

final_payments as (
    select
        validated_payments.payment_id,
        validated_payments.order_id,
        validated_payments.payment_date,
        validated_payments.payment_method,
        validated_payments.amount,
        case
            when validated_payments.order_total_amount is null then false
            when payment_aggregation.total_payments >= validated_payments.order_total_amount then true
            else false
        end as is_fully_applied,
        current_timestamp() as last_updated
    from validated_payments
    left join payment_aggregation
        on validated_payments.order_id = payment_aggregation.order_id
)

select
    payment_id,
    order_id,
    payment_date,
    payment_method,
    amount,
    is_fully_applied,
    last_updated
from final_payments