{#
------------------------------------------------------------------------
MODEL NAME    : fact_shipment
TARGET TABLE  : BSL_MA.DWH_MA.FACT_SHIPMENT
SOURCE TABLES : BSL_RAW.DWH_RAW.SHIPMENTS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model creates a fact table for shipments with 
                enriched data including days to ship calculation and 
                carrier information transformation
PREREQUISITES : Source tables SHIPMENTS and ORDERS must be available
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-20
------------------------------------------------------------------------
#}

{{ config(materialized='incremental') }}

with shipments_source as (
    select 
        shipment_id,
        order_id,
        shipped_date,
        carrier,
        tracking_number
    from {{ source('dwh_raw', 'shipments') }}
),

orders_source as (
    select 
        order_id,
        order_date
    from {{ source('dwh_raw', 'orders') }}
),

shipment_with_order_data as (
    select 
        shipments.shipment_id,
        shipments.order_id,
        shipments.shipped_date::date as shipped_date,
        upper(shipments.carrier) as carrier,
        shipments.tracking_number,
        orders.order_date,
        greatest(0, datediff('day', orders.order_date::date, shipments.shipped_date::date)) as days_to_ship,
        current_timestamp() as last_updated
    from shipments_source as shipments
    inner join orders_source as orders
        on shipments.order_id = orders.order_id
)

select 
    shipment_id,
    order_id,
    shipped_date,
    days_to_ship,
    carrier,
    tracking_number,
    last_updated
from shipment_with_order_data

{% if var('models')['backfill_flag'] == 'true' %}
where last_updated between '{{ var("models")["backfill_start_date"] }}' and '{{ var("models")["backfill_end_date"] }}'
{% endif %}

{% if is_incremental() %}
where last_updated > (select max(last_updated) from {{ this }})
{% endif %}