{#
------------------------------------------------------------------------
MODEL NAME    : fact_inventory
TARGET TABLE  : BSL_MA.DWH_MA.FACT_INVENTORY
SOURCE TABLES : BSL_RAW.DWH_RAW.INVENTORY
DESCRIPTION   : Inventory latest snapshot fact table with product and 
                supplier lookups, stock quantities, and warehouse locations
PREREQUISITES : dim_product and dim_supplier models must exist
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2025-11-19
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_inventory as (
    select 
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated
    from {{ source('dwh_raw', 'inventory') }}
),

product_lookup as (
    select 
        product_id
    from {{ ref('dim_product') }}
),

supplier_lookup as (
    select 
        supplier_id
    from {{ ref('dim_supplier') }}
),

inventory_with_flags as (
    select 
        source_inventory.product_id,
        source_inventory.supplier_id,
        source_inventory.stock_qty,
        source_inventory.warehouse_location,
        source_inventory.last_updated,
        row_number() over (
            partition by source_inventory.product_id, source_inventory.supplier_id 
            order by source_inventory.last_updated desc
        ) as row_num
    from source_inventory
),

final_inventory as (
    select 
        -- Product ID lookup with unknown handling
        coalesce(product_lookup.product_id, 
                case when inventory_with_flags.product_id is null then '0' 
                     else inventory_with_flags.product_id end) as product_id,
        
        -- Supplier ID lookup with unknown handling  
        coalesce(supplier_lookup.supplier_id,
                case when inventory_with_flags.supplier_id is null then '0'
                     else inventory_with_flags.supplier_id end) as supplier_id,
        
        -- Stock quantity with negative value handling
        case 
            when inventory_with_flags.stock_qty < 0 then null
            else inventory_with_flags.stock_qty 
        end as stock_qty,
        
        -- Warehouse location uppercase transformation
        upper(inventory_with_flags.warehouse_location) as warehouse_location,
        
        -- Convert timestamp to date for snapshot
        date(inventory_with_flags.last_updated) as snapshot_date,
        
        -- Flag for latest record per product and supplier
        case when inventory_with_flags.row_num = 1 then true else false end as is_latest
        
    from inventory_with_flags
    left join product_lookup 
        on inventory_with_flags.product_id = product_lookup.product_id
    left join supplier_lookup 
        on inventory_with_flags.supplier_id = supplier_lookup.supplier_id
)

select * from final_inventory