{#
------------------------------------------------------------------------
MODEL NAME    : fact_order_item
TARGET TABLE  : BSL_MA.DWH_MA.FACT_ORDER_ITEM
SOURCE TABLES : BSL_RAW.DWH_RAW.ORDER_ITEMS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model creates a fact table for order items with 
                calculated extended amounts, discount allocations, and 
                net amounts. Includes data quality checks and lookups.
PREREQUISITES : dim_product and fact_order models must exist
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-20
------------------------------------------------------------------------
#}

{{ config(materialized='incremental') }}

with source_order_items as (
    select 
        order_item_id,
        order_id,
        product_id,
        quantity,
        unit_price
    from {{ source('dwh_raw', 'order_items') }}
),

source_orders as (
    select 
        order_id
    from {{ source('dwh_raw', 'orders') }}
),

-- Validate order_id exists in orders table
validated_order_items as (
    select 
        oi.order_item_id,
        oi.order_id,
        oi.product_id,
        oi.quantity,
        oi.unit_price
    from source_order_items oi
    inner join source_orders ord
        on oi.order_id = ord.order_id
),

-- Handle product_id lookup and set to '0' if missing -- auto corrected using semantic file
product_validated_items as (
    select 
        voi.order_item_id,
        voi.order_id,
        coalesce(dp.product_id, '0') as product_id,
        voi.quantity,
        voi.unit_price
    from validated_order_items voi
    left join {{ ref('dim_product') }} dp
        on voi.product_id = dp.product_id
),

-- Calculate extended amount and other derived fields
final_calculations as (
    select 
        pvi.order_item_id,
        pvi.order_id,
        pvi.product_id,
        round(pvi.quantity) as quantity, -- Ensure integer semantics
        pvi.unit_price,
        round(pvi.quantity) * coalesce(pvi.unit_price, 0) as extended_amount,
        0.00 as discount_amount, -- Set to 0 as no discount context available
        current_timestamp() as last_updated
    from product_validated_items pvi
)

select 
    fc.order_item_id,
    fc.order_id,
    fc.product_id,
    fc.quantity,
    fc.unit_price,
    fc.extended_amount,
    fc.discount_amount,
    greatest(fc.extended_amount - fc.discount_amount, 0) as net_amount, -- Ensure non-negative
    fc.last_updated
from final_calculations fc

{% if var('models')['backfill_flag'] == 'true' %}
where fc.last_updated between '{{ var("models")["backfill_start_date"] }}' and '{{ var("models")["backfill_end_date"] }}'
{% endif %}

{% if is_incremental() %}
where fc.last_updated > (select max(last_updated) from {{ this }})
{% endif %}