{#
------------------------------------------------------------------------
MODEL NAME    : fact_order_item
TARGET TABLE  : BSL_MA.DWH_MA.FACT_ORDER_ITEM
SOURCE TABLES : BSL_RAW.DWH_RAW.ORDER_ITEMS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION   : This model creates a fact table for order items with 
                calculated extended amounts, discount allocations, and 
                net amounts. Includes product and order validations.
PREREQUISITES : dim_product and fact_order models must exist
PARAMETER     : backfill_flag, backfill_start_date, backfill_end_date
AUTHOUR       : AI Generated by Shajahan - 2025-11-21
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_item_id'
) }}

with source_order_items as (
    select 
        order_item_id,
        order_id,
        product_id,
        quantity,
        unit_price,
        inserted_at
    from {{ source('dwh_raw', 'order_items') }}
    {% if var('models')['backfill_flag'] == 'true' %}
        where inserted_at between '{{ var("models")["backfill_start_date"] }}' and '{{ var("models")["backfill_end_date"] }}'
    {% else %}
        {% if is_incremental() %}
            where inserted_at > (select max(inserted_at) from {{ this }})
        {% endif %}
    {% endif %}
),

source_orders as (
    select 
        order_id
    from {{ source('dwh_raw', 'orders') }}
),

validated_order_items as (
    select 
        oi.order_item_id,
        oi.order_id,
        case 
            when dp.product_id is null then '0'  -- auto corrected using semantic file: set to '0' if product missing
            else oi.product_id 
        end as product_id,
        round(oi.quantity) as quantity,  -- auto corrected using semantic file: ensure integer semantics
        coalesce(oi.unit_price, 0) as unit_price,  -- auto corrected using semantic file: treat null as 0
        oi.inserted_at
    from source_order_items oi
    inner join source_orders o on oi.order_id = o.order_id  -- auto corrected using semantic file: skip if order_id missing
    left join {{ ref('dim_product') }} dp on oi.product_id = dp.product_id
),

calculated_amounts as (
    select 
        voi.order_item_id,
        voi.order_id,
        voi.product_id,
        voi.quantity,
        voi.unit_price,
        (voi.quantity * voi.unit_price) as extended_amount,
        0 as discount_amount,  -- auto corrected using semantic file: set 0 if no discount context
        voi.inserted_at
    from validated_order_items voi
),

final_calculations as (
    select 
        ca.order_item_id,
        ca.order_id,
        ca.product_id,
        ca.quantity,
        ca.unit_price,
        ca.extended_amount,
        ca.discount_amount,
        greatest(0, ca.extended_amount - ca.discount_amount) as net_amount,  -- auto corrected using semantic file: ensure non-negative, floor at 0
        current_timestamp() as last_updated
    from calculated_amounts ca
)

select 
    order_item_id,
    order_id,
    product_id,
    quantity,
    unit_price,
    extended_amount,
    discount_amount,
    net_amount,
    last_updated
from final_calculations