version: 2
sources:
  - name: dwh_raw
    database: bsl_raw
    schema: dwh_raw
    description: Raw data warehouse schema containing source system tables for business operations including customers, orders, products, and related entities
    tables:
      - name: addresses
        description: The Addresses table stores information about the physical locations associated with customers, including the address details, city, and country, with each address uniquely identified by an Address ID and linked to a specific customer
        columns:
          - name: address_id
            description: Unique identifier for a specific address in the system
            data_type: varchar
          - name: customer_id
            description: Unique identifier for the customer associated with the address
            data_type: varchar
          - name: address_line1
            description: The street address or first line of the mailing address for a location
            data_type: varchar
          - name: city
            description: The city where the address is located
            data_type: varchar
          - name: country
            description: The country where the address is located
            data_type: varchar
          - name: inserted_at
            description: Date and time when the address record was inserted into the system
            data_type: date

      - name: categories
        description: This table stores information about categories in a hierarchical structure, allowing for subcategories. Each category is uniquely identified by a CATEGORY_ID and has a descriptive name
        columns:
          - name: category_id
            description: Unique identifier for a category in the catalog
            data_type: varchar
          - name: category_name
            description: This column represents the main categories of products sold, which can be used to group and analyze sales data by product type
            data_type: varchar
          - name: parent_category_id
            description: The parent category that this category belongs to, used to establish a hierarchical relationship between categories
            data_type: varchar
          - name: is_active
            description: Indicates whether a category is currently active and available for use
            data_type: boolean
          - name: created_at # auto corrected using semantic file
            description: Date and time when the category was created
            data_type: timestamp_ntz
          - name: inserted_at
            description: Date and time when the category was inserted into the system
            data_type: date

      - name: customers
        description: This table stores information about customers, including their unique identifier, name, email address, and the timestamp when their record was created
        columns:
          - name: customer_id
            description: Unique identifier for each customer in the database
            data_type: varchar
          - name: first_name # auto corrected using semantic file
            description: The first name of the customer
            data_type: varchar
          - name: last_name # auto corrected using semantic file
            description: The customer's last name
            data_type: varchar
          - name: email
            description: The email address of the customer
            data_type: varchar
          - name: created_at
            description: Date and time when the customer account was created
            data_type: timestamp_ntz
          - name: inserted_at
            description: Date and time when the customer record was inserted into the database
            data_type: date

      - name: inventory
        description: This table stores information about the current inventory levels of various products across different warehouses, including the supplier of each product, the quantity in stock, and the location within the warehouse
        columns:
          - name: product_id
            description: Unique identifier for a product in the inventory
            data_type: varchar
          - name: supplier_id
            description: Unique identifier for the supplier of the inventory item
            data_type: varchar
          - name: stock_qty
            description: The quantity of stock currently available in the inventory
            data_type: number
          - name: warehouse_location
            description: The physical location of the warehouse where the inventory is stored, represented by a combination of the state abbreviation and warehouse number
            data_type: varchar
          - name: last_updated
            description: The date and time when the inventory record was last updated
            data_type: timestamp_ntz
          - name: inserted_at
            description: Date and time when the inventory record was inserted into the system
            data_type: date

      - name: order_items
        description: This table stores information about individual items within an order, including the order and product details, quantity, and unit price, with a unique identifier for each order item
        columns:
          - name: order_item_id
            description: Unique identifier for each item within an order
            data_type: varchar
          - name: order_id
            description: Unique identifier for each order
            data_type: varchar
          - name: product_id
            description: Unique identifier for the product being ordered
            data_type: varchar
          - name: quantity
            description: The quantity of the item ordered
            data_type: number
          - name: unit_price
            description: The price of a single unit of an item in an order
            data_type: number
          - name: inserted_at
            description: The date and time when the order item was inserted into the system
            data_type: date

      - name: orders
        description: This table stores information about customer orders, including a unique order identifier, the customer who placed the order, the date the order was placed, the current status of the order, and the total amount of the order
        columns:
          - name: order_id
            description: Unique identifier for each order
            data_type: varchar
          - name: customer_id
            description: Unique identifier for the customer who placed the order
            data_type: varchar
          - name: order_date
            description: Date and time when the order was placed
            data_type: timestamp_ntz
          - name: status
            description: The current state of an order, indicating whether it has been successfully delivered to the customer, is in the process of being shipped, or has been cancelled
            data_type: varchar
          - name: total_amount
            description: The total amount of the order, including all items and any applicable taxes or fees
            data_type: number
          - name: inserted_at
            description: Date and time when the order was inserted into the system
            data_type: date

      - name: payments
        description: This table stores information about payments made for orders, including the payment method, date, and amount, with a unique identifier for each payment and a record of when the payment data was inserted into the system
        columns:
          - name: payment_id
            description: Unique identifier for each payment transaction
            data_type: varchar
          - name: order_id
            description: Unique identifier for the order that the payment was made against
            data_type: varchar
          - name: payment_date
            description: Date and time when the payment was made
            data_type: timestamp_ntz
          - name: payment_method
            description: The method used by the customer to make a payment, such as a debit card, credit card, or online payment service like PayPal
            data_type: varchar
          - name: amount
            description: The amount of payment made by a customer
            data_type: number
          - name: inserted_at
            description: Date and time when the payment was inserted into the system
            data_type: date

      - name: products
        description: This table stores information about products, including their unique identifier, name, category, price, and creation timestamp
        columns:
          - name: product_id
            description: Unique identifier for each product in the catalog
            data_type: varchar
          - name: product_name
            description: The name of the product being sold, such as a laptop, smartphone, or tablet, used to track sales and revenue by specific product model
            data_type: varchar
          - name: category_id # auto corrected using semantic file
            description: The CATEGORY_ID column represents the unique identifier for the product category to which a product belongs, allowing for grouping and analysis of products by category
            data_type: varchar
          - name: price
            description: The price of each product in the catalog, representing the amount that customers must pay to purchase the item
            data_type: number
          - name: created_at # auto corrected using semantic file
            description: Date and time when each product was created
            data_type: timestamp_ntz
          - name: inserted_at
            description: Date and time when the product was inserted into the system
            data_type: date

      - name: shipments
        description: This table stores information about shipments, including the unique shipment ID, the associated order ID, the date the shipment was made, the carrier used, and the tracking number
        columns:
          - name: shipment_id
            description: Unique identifier for each shipment
            data_type: varchar
          - name: order_id
            description: Unique identifier for each order
            data_type: varchar
          - name: shipped_date
            description: Date and time when the shipment was sent
            data_type: timestamp_ntz
          - name: carrier
            description: The shipping carrier responsible for transporting the shipment
            data_type: varchar
          - name: tracking_number
            description: Unique identifier assigned to a shipment for tracking purposes
            data_type: varchar
          - name: inserted_at
            description: Date and time when the shipment record was inserted into the system
            data_type: date

      - name: suppliers
        description: The Suppliers table stores information about external entities that provide goods or services to the organization, including their unique identifier, name, contact email, country of origin, and active status
        columns:
          - name: supplier_id
            description: Unique identifier for each supplier in the system
            data_type: varchar
          - name: supplier_name
            description: The name of the supplier company
            data_type: varchar
          - name: contact_email
            description: The email address of the primary contact for the supplier
            data_type: varchar
          - name: country
            description: The country of origin for the supplier
            data_type: varchar
          - name: active_flag
            description: Indicates whether the supplier is currently active and eligible to receive orders
            data_type: boolean
          - name: inserted_at
            description: Date and time when the supplier record was inserted into the system
            data_type: date