version: 2

sources:
  - name: dwh_raw
    database: bsl_raw
    schema: dwh_raw
    description: Raw data warehouse tables containing source system data
    tables:
      - name: addresses
        description: Customer address information with location details
        columns:
          - name: address_id
            description: Unique identifier for a specific address in the system
            data_type: varchar
          - name: customer_id
            description: Unique identifier for the customer associated with the address
            data_type: varchar
          - name: address_line1
            description: The street address or first line of the mailing address for a location
            data_type: varchar
          - name: city
            description: The city where the address is located
            data_type: varchar
          - name: country
            description: The country where the address is located
            data_type: varchar
          - name: inserted_at
            description: The date and time when the address record was inserted into the system
            data_type: timestamp_ntz

      - name: categories
        description: Product categories in hierarchical structure with parent-child relationships
        columns:
          - name: category_id
            description: Unique identifier for a category in the system
            data_type: varchar
          - name: category_name
            description: This column represents the main categories of products sold
            data_type: varchar
          - name: parent_category_id
            description: The parent category that this category belongs to
            data_type: varchar
          - name: is_active
            description: Indicates whether a category is currently active and available for use
            data_type: boolean
          - name: inserted_at  # auto corrected using semantic file
            description: Date and time when the category was inserted into the system
            data_type: timestamp_ntz

      - name: customers
        description: Individual customer information including contact details
        columns:
          - name: customer_id
            description: Unique identifier for each customer in the database
            data_type: varchar
          - name: first_name  # auto corrected using semantic file
            description: The first name of the customer
            data_type: varchar
          - name: last_name  # auto corrected using semantic file
            description: The customer's last name
            data_type: varchar
          - name: email
            description: The email address of the customer
            data_type: varchar
          - name: inserted_at
            description: Date and time when the customer record was inserted into the system
            data_type: timestamp_ntz

      - name: inventory
        description: Current inventory levels of products across different warehouses
        columns:
          - name: product_id
            description: Unique identifier for a product in the inventory
            data_type: varchar
          - name: supplier_id
            description: Unique identifier for the supplier of the inventory item
            data_type: varchar
          - name: stock_qty
            description: The quantity of stock currently available in the inventory
            data_type: number
          - name: warehouse_location
            description: The physical location of the warehouse where the inventory is stored
            data_type: varchar
          - name: last_updated
            description: The date and time when the inventory record was last updated
            data_type: timestamp_ntz

      - name: order_items
        description: Detailed information about each item within an order
        columns:
          - name: order_item_id
            description: Unique identifier for each item within an order
            data_type: varchar
          - name: order_id
            description: Unique identifier for the order that the item belongs to
            data_type: varchar
          - name: product_id
            description: Unique identifier for the product being ordered
            data_type: varchar
          - name: quantity
            description: The quantity of an item ordered
            data_type: number
          - name: unit_price
            description: The price of each individual item in an order
            data_type: number

      - name: orders
        description: Customer orders with status and total amount information
        columns:
          - name: order_id
            description: Unique identifier for each order
            data_type: varchar
          - name: customer_id
            description: Unique identifier for the customer who placed the order
            data_type: varchar
          - name: order_date
            description: Date and time when the order was placed
            data_type: timestamp_ntz
          - name: status
            description: The current state of an order
            data_type: varchar
          - name: total_amount
            description: The total amount of the order, including all items and any applicable taxes or fees
            data_type: number

      - name: payments
        description: Individual payments made by customers for orders
        columns:
          - name: payment_id
            description: Unique identifier for each payment transaction
            data_type: varchar
          - name: order_id
            description: Unique identifier for the order that the payment is associated with
            data_type: varchar
          - name: payment_date
            description: Date and time when the payment was made
            data_type: timestamp_ntz
          - name: payment_method
            description: The method used by the customer to make a payment
            data_type: varchar
          - name: amount
            description: The amount of payment made by a customer
            data_type: number

      - name: products
        description: Product catalog with pricing and category information
        columns:
          - name: product_id
            description: Unique identifier for each product in the catalog
            data_type: varchar
          - name: product_name
            description: The name of the product offered by the company
            data_type: varchar
          - name: price
            description: The price of each product in the catalog
            data_type: number
          - name: category_id  # auto corrected using semantic file
            description: The CATEGORY_ID column represents the unique identifier for the product category
            data_type: varchar
          - name: inserted_at  # auto corrected using semantic file
            description: Date and time when the product was inserted into the system
            data_type: timestamp_ntz

      - name: shipments
        description: Shipment information including carrier and tracking details
        columns:
          - name: shipment_id
            description: Unique identifier for a shipment
            data_type: varchar
          - name: order_id
            description: Unique identifier for each order
            data_type: varchar
          - name: shipped_date
            description: Date and time when the shipment was sent
            data_type: timestamp_ntz
          - name: carrier
            description: The shipping carrier responsible for transporting the shipment
            data_type: varchar
          - name: tracking_number
            description: Unique identifier assigned to a shipment for tracking purposes
            data_type: varchar

      - name: suppliers
        description: External suppliers with contact information and status
        columns:
          - name: supplier_id
            description: Unique identifier for each supplier in the system
            data_type: varchar
          - name: supplier_name
            description: The name of the supplier company
            data_type: varchar
          - name: contact_email
            description: The email address of the primary contact for the supplier
            data_type: varchar
          - name: country
            description: The country of origin for the supplier
            data_type: varchar
          - name: active_flag
            description: Indicates whether the supplier is currently active and eligible to receive orders
            data_type: boolean