version: 2

sources:
  - name: dwh_raw
    database: bsl_raw
    schema: dwh_raw
    description: "Raw data warehouse source tables"
    tables:
      - name: addresses
        description: "Customer address information"
        columns:
          - name: address_id
            description: "Unique identifier for address"
          - name: customer_id
            description: "Foreign key to customers table"
          - name: address_line1
            description: "Primary address line"
          - name: city
            description: "City name"
          - name: country
            description: "Country name"
          - name: inserted_at
            description: "Timestamp when record was inserted"

      - name: categories
        description: "Product category hierarchy"
        columns:
          - name: category_id
            description: "Unique identifier for category"
          - name: category_name
            description: "Name of the category"
          - name: parent_category_id
            description: "Parent category identifier for hierarchy"
          - name: is_active
            description: "Flag indicating if category is active"

      - name: customers
        description: "Customer master data"
        columns:
          - name: customer_id
            description: "Unique identifier for customer"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: inserted_at
            description: "Timestamp when customer record was created"

      - name: inventory
        description: "Product inventory levels by supplier and warehouse"
        columns:
          - name: product_id
            description: "Foreign key to products table"
          - name: supplier_id
            description: "Foreign key to suppliers table"
          - name: stock_qty
            description: "Current stock quantity"
          - name: warehouse_location
            description: "Warehouse location identifier"
          - name: last_updated
            description: "Timestamp of last inventory update"

      - name: order_items
        description: "Individual line items within orders"
        columns:
          - name: order_item_id
            description: "Unique identifier for order item"
          - name: order_id
            description: "Foreign key to orders table"
          - name: product_id
            description: "Foreign key to products table"
          - name: quantity
            description: "Quantity of product ordered"
          - name: unit_price
            description: "Price per unit of product"

      - name: orders
        description: "Customer order header information"
        columns:
          - name: order_id
            description: "Unique identifier for order"
          - name: customer_id
            description: "Foreign key to customers table"
          - name: order_date
            description: "Date when order was placed"
          - name: status
            description: "Current status of the order"
          - name: total_amount
            description: "Total monetary amount of the order"

      - name: payments
        description: "Payment transactions for orders"
        columns:
          - name: payment_id
            description: "Unique identifier for payment"
          - name: order_id
            description: "Foreign key to orders table"
          - name: payment_date
            description: "Date when payment was processed"
          - name: payment_method
            description: "Method used for payment"
          - name: amount
            description: "Payment amount"

      - name: products
        description: "Product catalog information"
        columns:
          - name: product_id
            description: "Unique identifier for product"
          - name: product_name
            description: "Name of the product"
          - name: price
            description: "Current price of the product"

      - name: shipments
        description: "Order shipment tracking information"
        columns:
          - name: shipment_id
            description: "Unique identifier for shipment"
          - name: order_id
            description: "Foreign key to orders table"
          - name: shipped_date
            description: "Date when order was shipped"
          - name: carrier
            description: "Shipping carrier name"
          - name: tracking_number
            description: "Carrier tracking number"

      - name: suppliers
        description: "Supplier master data"
        columns:
          - name: supplier_id
            description: "Unique identifier for supplier"
          - name: supplier_name
            description: "Name of the supplier"
          - name: contact_email
            description: "Supplier contact email"
          - name: country
            description: "Supplier country location"
          - name: active_flag
            description: "Flag indicating if supplier is active"