{#
------------------------------------------------------------------------
MODEL NAME    : dim_supplier
TARGET TABLE  : bsl_ma.dwh_ma.dim_supplier
SOURCE TABLES : bsl_raw.dwh_raw.suppliers
DESCRIPTION   : Dimension table for supplier information with data quality transformations
PREREQUISITES : Source table bsl_raw.dwh_raw.suppliers must exist
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2025-01-27 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_supplier'
) }}

WITH source_data AS (
    SELECT
        supplier_id,
        supplier_name,
        contact_email,
        country,
        active_flag
    FROM {{ source('dwh_raw', 'suppliers') }}
),

transformed AS (
    SELECT
        supplier_id,
        INITCAP(TRIM(supplier_name)) AS supplier_name,
        CASE 
            WHEN REGEXP_LIKE(LOWER(contact_email), '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')
            THEN LOWER(contact_email)
            ELSE NULL
        END AS contact_email,
        UPPER(country) AS country,
        COALESCE(active_flag, FALSE) AS is_active
    FROM source_data
)

SELECT * FROM transformed