{#
------------------------------------------------------------------------
MODEL NAME    : dim_category
TARGET TABLE  : bsl_ma.dwh_ma.dim_category
SOURCE TABLES : bsl_raw.dwh_raw.categories
DESCRIPTION   : Dimension table for product categories with hierarchical 
                path structure up to 2 levels
PREREQUISITES : Source table categories must exist in dwh_raw schema
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2025-01-27 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_category'
) }}

WITH source_data AS (
    SELECT
        category_id,
        category_name,
        parent_category_id,
        is_active
    FROM {{ source('dwh_raw', 'categories') }}
),

parent_categories AS (
    SELECT
        category_id AS parent_id,
        category_name AS parent_category_name
    FROM {{ source('dwh_raw', 'categories') }}
),

transformed AS (
    SELECT
        source_data.category_id,
        TRIM(INITCAP(source_data.category_name)) AS category_name,
        source_data.parent_category_id,
        CASE 
            WHEN source_data.parent_category_id IS NOT NULL 
            THEN CONCAT(
                TRIM(INITCAP(parent_categories.parent_category_name)), 
                ' > ', 
                TRIM(INITCAP(source_data.category_name))
            )
            ELSE TRIM(INITCAP(source_data.category_name))
        END AS category_path,
        COALESCE(source_data.is_active, TRUE) AS is_active
    FROM source_data
    LEFT JOIN parent_categories 
        ON source_data.parent_category_id = parent_categories.parent_id
)

SELECT * FROM transformed