{#
------------------------------------------------------------------------
MODEL NAME    : dim_address
TARGET TABLE  : bsl_ma.dwh_ma.dim_address
SOURCE TABLES : bsl_raw.dwh_raw.addresses
DESCRIPTION   : Dimension table for address information with customer lookup
                and data transformations including trimming and formatting
PREREQUISITES : dim_customer table must exist for customer_id lookup
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table'
) }}

WITH source_data AS (
    SELECT
        address_id,
        customer_id,
        address_line1,
        city,
        country,
        inserted_at
    FROM {{ source('dwh_raw', 'addresses') }}
),

customer_lookup AS (
    SELECT
        customer_id
    FROM {{ ref('dim_customer') }}
),

transformed AS (
    SELECT
        source_data.address_id,
        source_data.customer_id,
        TRIM(source_data.address_line1) AS address_line1,
        UPPER(source_data.city) AS city,
        source_data.country,
        DATE(source_data.inserted_at) AS inserted_at
    FROM source_data
    INNER JOIN customer_lookup
        ON source_data.customer_id = customer_lookup.customer_id
)

SELECT * FROM transformed