{#
------------------------------------------------------------------------
MODEL NAME    : dim_customer
TARGET TABLE  : bsl_ma.dwh_ma.dim_customer
SOURCE TABLES : bsl_raw.dwh_raw.customers, bsl_raw.dwh_raw.orders
DESCRIPTION   : Customer dimension table with derived spending tiers based on 
                purchase history and standardized customer attributes
PREREQUISITES : Source tables customers and orders must be available
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan
DATE          : 12 December 2025 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'view'
) }}

WITH customers_source AS (
    SELECT
        customer_id,
        first_name,
        last_name,
        email,
        inserted_at
    FROM {{ source('dwh_raw', 'customers') }}
),

orders_source AS (
    SELECT
        order_id,
        customer_id,
        total_amount,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
),

customer_spending AS (
    SELECT
        orders.customer_id,
        SUM(orders.total_amount) AS total_spending_365_days
    FROM orders_source AS orders
    WHERE orders.order_date >= DATEADD(day, -365, CURRENT_DATE())
    GROUP BY orders.customer_id
),

transformed AS (
    SELECT
        customers.customer_id,
        UPPER(TRIM(customers.first_name)) AS first_name,
        UPPER(TRIM(customers.last_name)) AS last_name,
        CASE 
            WHEN customers.email REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' 
            THEN LOWER(customers.email)
            ELSE NULL
        END AS email,
        COALESCE(DATE(customers.inserted_at), CURRENT_DATE()) AS customer_since_date,
        CASE 
            WHEN COALESCE(spending.total_spending_365_days, 0) >= 1000 THEN 'Gold'
            WHEN COALESCE(spending.total_spending_365_days, 0) >= 500 THEN 'Silver'
            ELSE 'Bronze'
        END AS customer_tier
    FROM customers_source AS customers
    LEFT JOIN customer_spending AS spending
        ON customers.customer_id = spending.customer_id
)

SELECT * FROM transformed