{#
------------------------------------------------------------------------
MODEL NAME    : dim_supplier
TARGET TABLE  : bsl_ma.dwh_ma.dim_supplier
SOURCE TABLES : bsl_raw.dwh_raw.suppliers
DESCRIPTION   : Dimension table for supplier information with data quality 
                transformations including email validation, name formatting,
                and country standardization
PREREQUISITES : Source table bsl_raw.dwh_raw.suppliers must exist
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table'
) }}

WITH source_data AS (
    SELECT
        supplier_id,
        supplier_name,
        contact_email,
        country,
        active_flag
    FROM {{ source('dwh_raw', 'suppliers') }}
),

transformed AS (
    SELECT
        suppliers.supplier_id AS supplier_id,
        TRIM(INITCAP(suppliers.supplier_name)) AS supplier_name,
        CASE 
            WHEN REGEXP_LIKE(LOWER(suppliers.contact_email), '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')
            THEN LOWER(suppliers.contact_email)
            ELSE NULL
        END AS contact_email,
        UPPER(suppliers.country) AS country,
        COALESCE(suppliers.active_flag, FALSE) AS is_active
    FROM source_data AS suppliers
)

SELECT * FROM transformed