{#
------------------------------------------------------------------------
MODEL NAME    : dim_product
TARGET TABLE  : bsl_ma.dwh_ma.dim_product
SOURCE TABLES : bsl_raw.dwh_raw.products
DESCRIPTION   : Dimension table for product information with price banding
                and data quality transformations
PREREQUISITES : Source table bsl_raw.dwh_raw.products must exist
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_product'
) }}

WITH source_data AS (
    SELECT
        product_id,
        product_name,
        price
    FROM {{ source('dwh_raw', 'products') }}
),

transformed AS (
    SELECT
        product_id,
        TRIM(INITCAP(product_name)) AS product_name,
        price,
        CASE 
            WHEN price < 50 THEN 'Low'
            WHEN price >= 50 AND price <= 199.99 THEN 'Mid'
            WHEN price >= 200 AND price <= 499.99 THEN 'High'
            WHEN price >= 500 THEN 'Premium'
        END AS price_band
    FROM source_data
)

SELECT * FROM transformed