
    {#
    ------------------------------------------------------------------------
    MODEL NAME    : dim_address
    TARGET TABLE  : bsl_ma.dwh_ma.dim_address
    SOURCE TABLES : bsl_raw.dwh_raw.addresses
    DESCRIPTION   : Dimension table for address information with customer lookup
                    and data transformations including trimming, case conversion
                    and timestamp to date conversion
    PREREQUISITES : dim_customer table must exist for customer_id lookup
    PARAMETER     : None
    AUTHOR        : AI Generated by Shajahan - 2024-12-19 (IST)
    ------------------------------------------------------------------------
    #}

    {{ config(
        materialized = 'table'
    ) }}

    WITH source_data AS (
        SELECT
            address_id,
            customer_id,
            address_line1,
            city,
            country,
            inserted_at
        FROM {{ source('dwh_raw', 'addresses') }}
    ),

    customer_lookup AS (
        SELECT
            customer_id
        FROM {{ ref('dim_customer') }}
    ),

    transformed AS (
        SELECT
            source_addresses.address_id,
            source_addresses.customer_id,
            TRIM(source_addresses.address_line1) AS address_line1,
            UPPER(source_addresses.city) AS city,
            source_addresses.country,
            DATE(source_addresses.inserted_at) AS inserted_at
        FROM source_data AS source_addresses
        INNER JOIN customer_lookup AS customer_dim
            ON source_addresses.customer_id = customer_dim.customer_id
    )

    SELECT * FROM transformed
