{#
------------------------------------------------------------------------
MODEL NAME    : dim_product
TARGET TABLE  : bsl_ma.dwh_ma.dim_product
SOURCE TABLES : bsl_raw.dwh_raw.products
DESCRIPTION   : Dimension table for product information with price banding
                and data quality transformations
PREREQUISITES : Source table bsl_raw.dwh_raw.products must exist
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_product'
) }}

WITH source_data AS (
    SELECT
        products.product_id,
        products.product_name,
        products.price
    FROM {{ source('dwh_raw', 'products') }} AS products
),

transformed AS (
    SELECT
        source_data.product_id,
        INITCAP(TRIM(source_data.product_name)) AS product_name,
        source_data.price,
        CASE 
            WHEN source_data.price < 50 THEN 'Low'
            WHEN source_data.price >= 50 AND source_data.price <= 199.99 THEN 'Mid'
            WHEN source_data.price >= 200 AND source_data.price <= 499.99 THEN 'High'
            WHEN source_data.price >= 500 THEN 'Premium'
            ELSE 'Unknown'
        END AS price_band
    FROM source_data
)

SELECT * FROM transformed