{#
------------------------------------------------------------------------
MODEL NAME    : fact_order
TARGET TABLE  : bsl_ma.dwh_ma.fact_order
SOURCE TABLES : bsl_raw.dwh_raw.orders
DESCRIPTION   : This model transforms raw order data into a fact table for
                analytical purposes. It includes order details, customer
                references, normalized status values, and validated amounts.
PREREQUISITES : dim_customer table must exist for customer lookup
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

WITH source_data AS (
    SELECT
        orders.order_id,
        orders.customer_id,
        orders.order_date,
        orders.status,
        orders.total_amount
    FROM {{ source('dwh_raw', 'orders') }} AS orders
    {% if is_incremental() %}
        WHERE orders.order_date::date > (select coalesce(max(order_date), '1900-01-01') from {{ this }})
    {% endif %}
),

customer_lookup AS (
    SELECT
        dim_customer.customer_id
    FROM {{ ref('dim_customer') }} AS dim_customer
),

transformed AS (
    SELECT
        source_data.order_id,
        source_data.customer_id,
        source_data.order_date::date AS order_date,
        CASE 
            WHEN UPPER(source_data.status) IN ('PENDING', 'CANCELLED', 'SHIPPED', 'DELIVERED') 
            THEN UPPER(source_data.status)
            ELSE 'PENDING'
        END AS order_status,
        CASE 
            WHEN source_data.total_amount < 0 
            THEN NULL
            ELSE source_data.total_amount
        END AS total_amount
    FROM source_data
    INNER JOIN customer_lookup
        ON source_data.customer_id = customer_lookup.customer_id
)

SELECT * FROM transformed