{#
------------------------------------------------------------------------
MODEL NAME    : fact_order
TARGET TABLE  : bsl_ma.dwh_ma.fact_order
SOURCE TABLES : bsl_raw.dwh_raw.orders
DESCRIPTION   : This model transforms raw order data into a business-ready fact table
                with proper data type conversions, status normalization, and customer
                validation through dimension table lookup.
PREREQUISITES : dim_customer table must exist for customer validation
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    unique_key = 'order_id'
) }}

WITH source_data AS (
    SELECT
        order_id,
        customer_id,
        order_date,
        status,
        total_amount
    FROM {{ source('dwh_raw', 'orders') }}
    {% if is_incremental() %}
        WHERE order_date::date > (select coalesce(max(order_date), '1900-01-01') from {{ this }})
    {% endif %}
),

customer_lookup AS (
    SELECT
        customer_id
    FROM {{ ref('dim_customer') }}
),

transformed AS (
    SELECT
        source_data.order_id,
        source_data.customer_id,
        source_data.order_date::date as order_date,
        CASE 
            WHEN UPPER(source_data.status) IN ('PENDING', 'CANCELLED', 'SHIPPED', 'DELIVERED') 
            THEN UPPER(source_data.status)
            ELSE 'PENDING'
        END as order_status,
        CASE 
            WHEN source_data.total_amount < 0 
            THEN NULL
            ELSE source_data.total_amount
        END as total_amount
    FROM source_data
    INNER JOIN customer_lookup
        ON source_data.customer_id = customer_lookup.customer_id
)

SELECT * FROM transformed