{#
------------------------------------------------------------------------
MODEL NAME    : fact_inventory
TARGET TABLE  : bsl_ma.dwh_ma.fact_inventory
SOURCE TABLES : bsl_raw.dwh_raw.inventory
DESCRIPTION   : Inventory latest snapshot fact table with product and supplier lookups
PREREQUISITES : dim_product and dim_supplier tables must exist
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'fact_inventory'
) }}

WITH source_data AS (
    SELECT
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated
    FROM {{ source('dwh_raw', 'inventory') }}
),

product_lookup AS (
    SELECT
        product_id
    FROM {{ ref('dim_product') }}
),

supplier_lookup AS (
    SELECT
        supplier_id
    FROM {{ ref('dim_supplier') }}
),

latest_records AS (
    SELECT
        source_data.product_id,
        source_data.supplier_id,
        source_data.stock_qty,
        source_data.warehouse_location,
        source_data.last_updated,
        ROW_NUMBER() OVER (
            PARTITION BY source_data.product_id, source_data.supplier_id 
            ORDER BY source_data.last_updated DESC
        ) as row_number
    FROM source_data
),

transformed AS (
    SELECT
        COALESCE(product_lookup.product_id, '0') as product_id,
        COALESCE(supplier_lookup.supplier_id, '0') as supplier_id,
        CASE 
            WHEN latest_records.stock_qty < 0 THEN NULL 
            ELSE latest_records.stock_qty 
        END as stock_qty,
        UPPER(latest_records.warehouse_location) as warehouse_location,
        DATE(latest_records.last_updated) as snapshot_date,
        CASE 
            WHEN latest_records.row_number = 1 THEN TRUE 
            ELSE FALSE 
        END as is_latest
    FROM latest_records
    LEFT JOIN product_lookup 
        ON latest_records.product_id = product_lookup.product_id
    LEFT JOIN supplier_lookup 
        ON latest_records.supplier_id = supplier_lookup.supplier_id
)

SELECT * FROM transformed