{#
------------------------------------------------------------------------
MODEL NAME    : fact_shipment
TARGET TABLE  : bsl_ma.dwh_ma.fact_shipment
SOURCE TABLES : bsl_raw.dwh_raw.shipments, bsl_raw.dwh_raw.orders
DESCRIPTION   : This model creates a fact table for shipment data by combining
                shipment information with order details to calculate shipping
                metrics and provide comprehensive shipment analytics
PREREQUISITES : Source tables shipments and orders must exist with valid data
PARAMETER     : Incremental model with shipment_date based filtering
AUTHOUR       : AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    unique_key = 'shipment_id'
) }}

WITH shipments_source AS (
    SELECT
        shipment_id,
        order_id,
        shipped_date,
        carrier,
        tracking_number
    FROM {{ source('dwh_raw', 'shipments') }}
    {% if is_incremental() %}
        WHERE shipped_date::date > (select coalesce(max(shipped_date), '1900-01-01') from {{ this }})
    {% endif %}
),

orders_source AS (
    SELECT
        order_id,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
),

shipments_with_orders AS (
    SELECT
        shipments_source.shipment_id,
        shipments_source.order_id,
        shipments_source.shipped_date::date as shipped_date,
        UPPER(shipments_source.carrier) as carrier,
        shipments_source.tracking_number,
        orders_source.order_date
    FROM shipments_source
    LEFT JOIN orders_source
        ON shipments_source.order_id = orders_source.order_id
    WHERE orders_source.order_id IS NOT NULL
),

final_transformations AS (
    SELECT
        shipment_id,
        order_id,
        shipped_date,
        carrier,
        tracking_number,
        GREATEST(0, DATEDIFF('day', order_date::date, shipped_date)) as days_to_ship
    FROM shipments_with_orders
)

SELECT * FROM final_transformations