{#
------------------------------------------------------------------------
MODEL NAME    : fact_order_item
TARGET TABLE  : bsl_ma.dwh_ma.fact_order_item
SOURCE TABLES : bsl_raw.dwh_raw.order_items, bsl_raw.dwh_raw.orders
DESCRIPTION   : Fact table containing order item level details with 
                calculated amounts, product lookups, and order validations
PREREQUISITES : dim_product and fact_order tables must exist
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    unique_key = 'order_item_id'
) }}

WITH source_order_items AS (
    SELECT
        order_item_id,
        order_id,
        product_id,
        quantity,
        unit_price
    FROM {{ source('dwh_raw', 'order_items') }}
    {% if is_incremental() %}
        WHERE exists (select 1 where true) and {{ is_incremental() }}
    {% endif %}
),

source_orders AS (
    SELECT
        order_id
    FROM {{ source('dwh_raw', 'orders') }}
),

fact_order_lookup AS (
    SELECT
        order_id
    FROM {{ ref('fact_order') }}
),

dim_product_lookup AS (
    SELECT
        product_id
    FROM {{ ref('dim_product') }}
),

validated_order_items AS (
    SELECT
        source_order_items.order_item_id,
        source_order_items.order_id,
        CASE 
            WHEN dim_product_lookup.product_id IS NULL THEN '0'
            ELSE source_order_items.product_id
        END AS product_id,
        ROUND(source_order_items.quantity) AS quantity,
        source_order_items.unit_price
    FROM source_order_items
    INNER JOIN fact_order_lookup 
        ON source_order_items.order_id = fact_order_lookup.order_id
    LEFT JOIN dim_product_lookup 
        ON source_order_items.product_id = dim_product_lookup.product_id
),

calculated_amounts AS (
    SELECT
        validated_order_items.order_item_id,
        validated_order_items.order_id,
        validated_order_items.product_id,
        validated_order_items.quantity,
        validated_order_items.unit_price,
        (validated_order_items.quantity * COALESCE(validated_order_items.unit_price, 0))::NUMBER(12,2) AS extended_amount,
        0::NUMBER(12,2) AS discount_amount
    FROM validated_order_items
),

final_calculations AS (
    SELECT
        calculated_amounts.order_item_id,
        calculated_amounts.order_id,
        calculated_amounts.product_id,
        calculated_amounts.quantity,
        calculated_amounts.unit_price::NUMBER(10,2) AS unit_price,
        calculated_amounts.extended_amount,
        calculated_amounts.discount_amount,
        GREATEST(0, calculated_amounts.extended_amount - calculated_amounts.discount_amount)::NUMBER(12,2) AS net_amount
    FROM calculated_amounts
)

SELECT * FROM final_calculations