{#
------------------------------------------------------------------------
MODEL NAME    : fact_order_item
TARGET TABLE  : bsl_ma.dwh_ma.fact_order_item
SOURCE TABLES : bsl_raw.dwh_raw.order_items, bsl_raw.dwh_raw.orders
DESCRIPTION   : Fact table for order items containing detailed item-level 
                information including quantities, prices, and calculated amounts
PREREQUISITES : Source tables order_items and orders must exist with valid data
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_item_id'
) }}

WITH source_order_items AS (
    SELECT
        order_item_id,
        order_id,
        product_id,
        quantity,
        unit_price
    FROM {{ source('dwh_raw', 'order_items') }}
    {% if is_incremental() %}
        WHERE exists (select 1 where true) and {{ is_incremental() }}
    {% endif %}
),

source_orders AS (
    SELECT
        order_id
    FROM {{ source('dwh_raw', 'orders') }}
),

fact_order_reference AS (
    SELECT
        order_id
    FROM {{ ref('fact_order') }}
),

dim_product_reference AS (
    SELECT
        product_id
    FROM {{ ref('dim_product') }}
),

validated_order_items AS (
    SELECT
        source_items.order_item_id,
        source_items.order_id,
        COALESCE(source_items.product_id, '0') AS product_id,
        ROUND(source_items.quantity) AS quantity,
        source_items.unit_price
    FROM source_order_items AS source_items
    INNER JOIN fact_order_reference AS fact_order_ref
        ON source_items.order_id = fact_order_ref.order_id
),

calculated_amounts AS (
    SELECT
        validated_items.order_item_id,
        validated_items.order_id,
        validated_items.product_id,
        validated_items.quantity,
        validated_items.unit_price,
        (validated_items.quantity * COALESCE(validated_items.unit_price, 0)) AS extended_amount,
        0 AS discount_amount
    FROM validated_order_items AS validated_items
),

final_calculations AS (
    SELECT
        calc_amounts.order_item_id,
        calc_amounts.order_id,
        calc_amounts.product_id,
        calc_amounts.quantity,
        calc_amounts.unit_price,
        calc_amounts.extended_amount,
        calc_amounts.discount_amount,
        GREATEST(0, calc_amounts.extended_amount - calc_amounts.discount_amount) AS net_amount
    FROM calculated_amounts AS calc_amounts
)

SELECT * FROM final_calculations