{#
------------------------------------------------------------------------
MODEL NAME    : fact_payment
TARGET TABLE  : bsl_ma.dwh_ma.fact_payment
SOURCE TABLES : bsl_raw.dwh_raw.payments, bsl_raw.dwh_raw.orders
DESCRIPTION   : This model creates a fact table for payment transactions with 
                order validation and payment method standardization. It includes
                derived fields for payment application status and data quality
                transformations.
PREREQUISITES : fact_order table must exist for order validation
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    unique_key = 'payment_id'
) }}

with payments_source as (
    select
        payment_id,
        order_id,
        payment_date,
        payment_method,
        amount
    from {{ source('dwh_raw', 'payments') }}
    {% if is_incremental() %}
        where payment_date::date > (select coalesce(max(payment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

orders_source as (
    select
        order_id,
        total_amount
    from {{ source('dwh_raw', 'orders') }}
),

fact_order_ref as (
    select
        order_id,
        total_amount
    from {{ ref('fact_order') }}
),

payment_aggregates as (
    select
        payments_source.order_id,
        sum(case when payments_source.amount >= 0 then payments_source.amount else 0 end) as total_payments
    from payments_source
    inner join fact_order_ref on payments_source.order_id = fact_order_ref.order_id
    group by payments_source.order_id
),

transformed as (
    select
        payments_source.payment_id,
        payments_source.order_id,
        payments_source.payment_date::date as payment_date,
        case 
            when upper(payments_source.payment_method) in ('CARD', 'UPI', 'COD', 'NETBANKING') 
            then upper(payments_source.payment_method)
            else 'CARD'
        end as payment_method,
        case 
            when payments_source.amount < 0 then null
            else payments_source.amount
        end as amount,
        case 
            when fact_order_ref.total_amount is null then false
            when payment_aggregates.total_payments >= fact_order_ref.total_amount then true
            else false
        end as is_fully_applied
    from payments_source
    inner join fact_order_ref on payments_source.order_id = fact_order_ref.order_id
    left join payment_aggregates on payments_source.order_id = payment_aggregates.order_id
)

select * from transformed