{#
------------------------------------------------------------------------
MODEL NAME    : fact_payment
TARGET TABLE  : bsl_ma.dwh_ma.fact_payment
SOURCE TABLES : bsl_raw.dwh_raw.payments, bsl_raw.dwh_raw.orders
DESCRIPTION   : This model creates a fact table for payment transactions by 
                transforming raw payment data with order validations and 
                business logic transformations including payment method 
                standardization and full payment application flags.
PREREQUISITES : fact_order model must exist for order lookups
PARAMETER     : Incremental model with payment_date based filtering
AUTHOR        : AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    unique_key = 'payment_id'
) }}

WITH payments_source AS (
    SELECT
        payment_id,
        order_id,
        payment_date,
        payment_method,
        amount
    FROM {{ source('dwh_raw', 'payments') }}
    {% if is_incremental() %}
        WHERE payment_date::date > (select coalesce(max(payment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

orders_source AS (
    SELECT
        order_id,
        total_amount
    FROM {{ source('dwh_raw', 'orders') }}
),

fact_order_ref AS (
    SELECT
        order_id
    FROM {{ ref('fact_order') }}
),

payment_aggregates AS (
    SELECT
        payments_source.order_id,
        SUM(payments_source.amount) AS total_payments
    FROM payments_source
    GROUP BY payments_source.order_id
),

transformed AS (
    SELECT
        payments_source.payment_id,
        payments_source.order_id,
        payments_source.payment_date::date AS payment_date,
        CASE 
            WHEN UPPER(payments_source.payment_method) IN ('CARD', 'UPI', 'COD', 'NETBANKING') 
            THEN UPPER(payments_source.payment_method)
            ELSE 'CARD'
        END AS payment_method,
        CASE 
            WHEN payments_source.amount < 0 THEN NULL
            ELSE payments_source.amount
        END AS amount,
        CASE 
            WHEN orders_source.total_amount IS NULL THEN FALSE
            WHEN payment_aggregates.total_payments >= orders_source.total_amount THEN TRUE
            ELSE FALSE
        END AS is_fully_applied
    FROM payments_source
    INNER JOIN fact_order_ref 
        ON payments_source.order_id = fact_order_ref.order_id
    LEFT JOIN orders_source 
        ON payments_source.order_id = orders_source.order_id
    LEFT JOIN payment_aggregates 
        ON payments_source.order_id = payment_aggregates.order_id
)

SELECT * FROM transformed