version: 2
sources:
- name: dwh_raw
  database: bsl_raw
  schema: dwh_raw
  description: Raw data warehouse schema containing source tables for e-commerce operations
  tables:
  - name: addresses
    description: Customer address information with location details
    columns:
    - name: address_id
      description: Unique identifier for each address record
    - name: customer_id
      description: Foreign key reference to customers table
    - name: address_line1
      description: Primary address line containing street information
    - name: city
      description: City name for the address
    - name: country
      description: Country name for the address
    - name: inserted_at
      description: Timestamp when the address record was created
  - name: categories
    description: Product category hierarchy with parent-child relationships
    columns:
    - name: category_id
      description: Unique identifier for each category
    - name: category_name
      description: Name of the product category
    - name: parent_category_id
      description: Reference to parent category for hierarchical structure
    - name: is_active
      description: Flag indicating if category is currently active, defaults to true if null
  - name: customers
    description: Customer master data with personal information
    columns:
    - name: customer_id
      description: Unique identifier for each customer
    - name: first_name
      description: Customer's first name
    - name: last_name
      description: Customer's last name
    - name: email
      description: Customer's email address
    - name: inserted_at
      description: Timestamp when customer record was created, defaults to current_date if null
  - name: inventory
    description: Product inventory levels by supplier and warehouse location
    columns:
    - name: product_id
      description: Reference to product identifier
    - name: supplier_id
      description: Reference to supplier identifier
    - name: stock_qty
      description: Current stock quantity available
    - name: warehouse_location
      description: Physical location where inventory is stored
    - name: last_updated
      description: Timestamp of last inventory update, used to identify latest records
  - name: order_items
    description: Individual line items within customer orders
    columns:
    - name: order_item_id
      description: Unique identifier for each order line item
    - name: order_id
      description: Reference to parent order
    - name: product_id
      description: Reference to ordered product
    - name: quantity
      description: Number of units ordered
    - name: unit_price
      description: Price per unit for the product
  - name: orders
    description: Customer order header information with status and totals
    columns:
    - name: order_id
      description: Unique identifier for each order
    - name: customer_id
      description: Reference to customer who placed the order
    - name: order_date
      description: Date when order was placed
    - name: status
      description: Current status of the order
    - name: total_amount
      description: Total monetary value of the order
  - name: payments
    description: Payment transactions associated with orders
    columns:
    - name: payment_id
      description: Unique identifier for each payment transaction
    - name: order_id
      description: Reference to associated order
    - name: payment_date
      description: Date when payment was processed
    - name: payment_method
      description: Method used for payment processing
    - name: amount
      description: Payment amount, set to null if negative
  - name: products
    description: Product catalog with pricing information
    columns:
    - name: product_id
      description: Unique identifier for each product
    - name: product_name
      description: Name of the product
    - name: price
      description: Product price used for bucketing into Low/Mid/High/Premium categories
  - name: shipments
    description: Shipping information for order fulfillment
    columns:
    - name: shipment_id
      description: Unique identifier for each shipment
    - name: order_id
      description: Reference to associated order
    - name: shipped_date
      description: Date when shipment was dispatched
    - name: carrier
      description: Shipping carrier company
    - name: tracking_number
      description: Carrier-provided tracking identifier
  - name: suppliers
    description: Supplier master data with contact information
    columns:
    - name: supplier_id
      description: Unique identifier for each supplier
    - name: supplier_name
      description: Name of the supplier company
    - name: contact_email
      description: Primary contact email for the supplier
    - name: country
      description: Country where supplier is located
    - name: active_flag
      description: Flag indicating if supplier is active, defaults to false if null