version: 2
sources:
- name: dwh_raw
  database: bsl_raw
  schema: dwh_raw
  description: Raw data warehouse schema containing source system data
  tables:
  - name: addresses
    description: Customer address information table
    columns:
    - name: address_id
      description: Unique identifier for each address record
    - name: customer_id
      description: Foreign key reference to customer table
    - name: address_line1
      description: Primary address line containing street information
    - name: city
      description: City name for the address
    - name: country
      description: Country name for the address
    - name: inserted_at
      description: Timestamp when the record was inserted into the system
  - name: categories
    description: Product category hierarchy table
    columns:
    - name: category_id
      description: Unique identifier for each category
    - name: category_name
      description: Name of the product category
    - name: parent_category_id
      description: Foreign key reference to parent category for hierarchy
    - name: is_active
      description: Boolean flag indicating if category is active, defaults to true when null